### ISSUE TITLE
ImportError: cannot import name 'TrainingProcessor'

### ISSUE THREAD

**Issue by nerdprogrammergm** [deepfakes/faceswap#25] opened 2017-12-25 11:23 UTC
You latest commit brought me some new error, help me to play around and fix em please.
from lib.cli import TrainingProcessor

**Comment by Ganonmaster** [comment] 2017-12-25 12:50
I just tested this, and am unable to reproduce your error. Please verify that you are running `faceswap.py` from the project directory, are specifying the correct arguments and that all the dependencies are installed in your environment.

**Comment by Ganonmaster** [comment] 2017-12-26 21:53
Closing this for now as it does not seem to be a code bug. If there is a structural issue, it can be re-opened. Meanwhile, ask your question on the faceswap-playground. https://github.com/deepfakes/faceswap-playground

**Closed** 2017-12-26 21:54 UTC
