### ISSUE TITLE
crash in converting ffmpeg writer

### ISSUE THREAD

**Issue by myselfbeinghuman** [deepfakes/faceswap#1064] opened 2020-09-13 03:21 UTC
```
09/13/2020 07:56:14 MainProcess     patch_10        convert         process                   DEBUG    Completed convert process
09/13/2020 07:56:14 MainProcess     MainThread      multithreading  completed                 DEBUG    False
09/13/2020 07:56:15 MainProcess     patch_11        convert         process                   DEBUG    EOF Received
09/13/2020 07:56:15 MainProcess     patch_11        convert         process                   DEBUG    Patch queue finished
09/13/2020 07:56:15 MainProcess     patch_11        convert         process                   DEBUG    Putting EOF back to in_queue
09/13/2020 07:56:15 MainProcess     patch_11        convert         process                   DEBUG    Completed convert process
09/13/2020 07:56:15 MainProcess     MainThread      multithreading  completed                 DEBUG    False
09/13/2020 07:56:16 MainProcess     _save_0         convert         _save                     DEBUG    Writing GUI Preview image: 'D:\aa Faceswap MODELS\outpu\.gui_preview.jpg'
09/13/2020 07:56:16 MainProcess     MainThread      multithreading  completed                 DEBUG    False
09/13/2020 07:56:17 MainProcess     MainThread      multithreading  completed                 DEBUG    False
09/13/2020 07:56:18 MainProcess     MainThread      multithreading  completed                 DEBUG    False
09/13/2020 07:56:19 MainProcess     _save_0         convert         _save                     DEBUG    Writing GUI Preview image: 'D:\aa Faceswap MODELS\outpu\.gui_preview.jpg'
09/13/2020 07:56:19 MainProcess     MainThread      multithreading  completed                 DEBUG    False
09/13/2020 07:56:20 MainProcess     MainThread      multithreading  completed                 DEBUG    False
09/13/2020 07:56:21 MainProcess     MainThread      multithreading  completed                 DEBUG    False
09/13/2020 07:56:22 MainProcess     MainThread      multithreading  completed                 DEBUG    False
09/13/2020 07:56:23 MainProcess     MainThread      multithreading  completed                 DEBUG    False
09/13/2020 07:56:24 MainProcess     MainThread      multithreading  completed                 DEBUG    False
09/13/2020 07:56:25 MainProcess     MainThread      multithreading  completed                 DEBUG    False
09/13/2020 07:56:26 MainProcess     MainThread      multithreading  completed                 DEBUG    False
09/13/2020 07:56:27 MainProcess     MainThread      multithreading  completed                 DEBUG    False
09/13/2020 07:56:28 MainProcess     MainThread      multithreading  completed                 DEBUG    False
09/13/2020 07:56:29 MainProcess     MainThread      multithreading  completed                 DEBUG    False
09/13/2020 07:56:30 MainProcess     patch_8         convert         process                   DEBUG    EOF Received
09/13/2020 07:56:30 MainProcess     patch_8         convert         process                   DEBUG    Patch queue finished
09/13/2020 07:56:30 MainProcess     patch_8         convert         process                   DEBUG    Putting EOF back to in_queue
09/13/2020 07:56:30 MainProcess     patch_8         convert         process                   DEBUG    Completed convert process
09/13/2020 07:56:30 MainProcess     MainThread      multithreading  completed                 DEBUG    False
09/13/2020 07:56:31 MainProcess     MainThread      multithreading  completed                 DEBUG    False
09/13/2020 07:56:32 MainProcess     MainThread      multithreading  completed                 DEBUG    False
09/13/2020 07:56:33 MainProcess     MainThread      multithreading  completed                 DEBUG    False
09/13/2020 07:56:34 MainProcess     MainThread      multithreading  completed                 DEBUG    False
09/13/2020 07:56:35 MainProcess     MainThread      multithreading  completed                 DEBUG    False
09/13/2020 07:56:36 MainProcess     MainThread      multithreading  completed                 DEBUG    False
09/13/2020 07:56:37 MainProcess     MainThread      multithreading  completed                 DEBUG    False
09/13/2020 07:56:38 MainProcess     MainThread      multithreading  completed                 DEBUG    False
09/13/2020 07:56:39 MainProcess     MainThread      multithreading  completed                 DEBUG    False
09/13/2020 07:56:40 MainProcess     patch_0         convert         process                   DEBUG    EOF Received
09/13/2020 07:56:40 MainProcess     patch_0         convert         process                   DEBUG    Patch queue finished
09/13/2020 07:56:40 MainProcess     patch_0         convert         process                   DEBUG    Putting EOF back to in_queue
09/13/2020 07:56:40 MainProcess     patch_0         convert         process                   DEBUG    Completed convert process
09/13/2020 07:56:40 MainProcess     MainThread      multithreading  completed                 DEBUG    False
09/13/2020 07:56:41 MainProcess     MainThread      multithreading  completed                 DEBUG    False
09/13/2020 07:56:42 MainProcess     patch_1         convert         process                   DEBUG    EOF Received
09/13/2020 07:56:42 MainProcess     patch_1         convert         process                   DEBUG    Patch queue finished
09/13/2020 07:56:42 MainProcess     patch_1         convert         process                   DEBUG    Putting EOF back to in_queue
09/13/2020 07:56:42 MainProcess     patch_1         convert         process                   DEBUG    Completed convert process
09/13/2020 07:56:42 MainProcess     MainThread      multithreading  completed                 DEBUG    False
09/13/2020 07:56:43 MainProcess     MainThread      multithreading  completed                 DEBUG    False
09/13/2020 07:56:44 MainProcess     patch_2         convert         process                   DEBUG    EOF Received
09/13/2020 07:56:44 MainProcess     patch_2         convert         process                   DEBUG    Patch queue finished
09/13/2020 07:56:44 MainProcess     patch_2         convert         process                   DEBUG    Putting EOF back to in_queue
09/13/2020 07:56:44 MainProcess     patch_2         convert         process                   DEBUG    Completed convert process
09/13/2020 07:56:44 MainProcess     MainThread      multithreading  completed                 DEBUG    False
09/13/2020 07:56:45 MainProcess     patch_3         convert         process                   DEBUG    EOF Received
09/13/2020 07:56:45 MainProcess     patch_3         convert         process                   DEBUG    Patch queue finished
09/13/2020 07:56:45 MainProcess     patch_3         convert         process                   DEBUG    Putting EOF back to in_queue
09/13/2020 07:56:45 MainProcess     patch_3         convert         process                   DEBUG    Completed convert process
09/13/2020 07:56:45 MainProcess     MainThread      multithreading  completed                 DEBUG    False
09/13/2020 07:56:46 MainProcess     MainThread      multithreading  completed                 DEBUG    False
09/13/2020 07:56:47 MainProcess     patch_4         convert         process                   DEBUG    EOF Received
09/13/2020 07:56:47 MainProcess     patch_4         convert         process                   DEBUG    Patch queue finished
09/13/2020 07:56:47 MainProcess     patch_4         convert         process                   DEBUG    Putting EOF back to in_queue
09/13/2020 07:56:47 MainProcess     patch_4         convert         process                   DEBUG    Completed convert process
09/13/2020 07:56:47 MainProcess     MainThread      multithreading  completed                 DEBUG    False
09/13/2020 07:56:48 MainProcess     patch_5         convert         process                   DEBUG    EOF Received
09/13/2020 07:56:48 MainProcess     patch_5         convert         process                   DEBUG    Patch queue finished
09/13/2020 07:56:48 MainProcess     patch_5         convert         process                   DEBUG    Putting EOF back to in_queue
09/13/2020 07:56:48 MainProcess     patch_5         convert         process                   DEBUG    Completed convert process
09/13/2020 07:56:48 MainProcess     MainThread      multithreading  completed                 DEBUG    False
09/13/2020 07:56:49 MainProcess     patch_6         convert         process                   DEBUG    EOF Received
09/13/2020 07:56:49 MainProcess     patch_6         convert         process                   DEBUG    Patch queue finished
09/13/2020 07:56:49 MainProcess     patch_6         convert         process                   DEBUG    Putting EOF back to in_queue
09/13/2020 07:56:49 MainProcess     patch_6         convert         process                   DEBUG    Completed convert process
09/13/2020 07:56:49 MainProcess     MainThread      multithreading  completed                 DEBUG    False
09/13/2020 07:56:50 MainProcess     patch_7         convert         process                   DEBUG    EOF Received
09/13/2020 07:56:50 MainProcess     patch_7         convert         process                   DEBUG    Patch queue finished
09/13/2020 07:56:50 MainProcess     patch_7         convert         process                   DEBUG    Putting EOF back to in_queue
09/13/2020 07:56:50 MainProcess     patch_7         convert         process                   DEBUG    Completed convert process
09/13/2020 07:56:50 MainProcess     _save_0         ffmpeg          mux_audio                 INFO     Muxing Audio...
09/13/2020 07:56:50 MainProcess     _save_0         ffmpeg          video_file                DEBUG    D:\aa Faceswap MODELS\outpu\seta_converted.mp4
09/13/2020 07:56:50 MainProcess     _save_0         ffmpeg          video_tmp_file            DEBUG    D:\aa Faceswap MODELS\outpu\__tmp_seta_converted.mp4
09/13/2020 07:56:50 MainProcess     _save_0         ffmpeg          video_file                DEBUG    D:\aa Faceswap MODELS\outpu\seta_converted.mp4
09/13/2020 07:56:50 MainProcess     _save_0         ffmpeg          mux_audio                 DEBUG    Executing: C:\Users\Anshaj\Anaconda3\envs\faceswap\Library\bin\ffmpeg.exe -hide_banner -nostats -v 0 -y -i "D:\aa Faceswap MODELS\outpu\__tmp_seta_converted.mp4" -i "D:\aa Faceswap MODELS\seta.mp4" -map 0:v:0 -map 1:a:0 -c: copy "D:\aa Faceswap MODELS\outpu\seta_converted.mp4"
09/13/2020 07:56:50 MainProcess     _save_0         ffmpeg          mux_audio                 DEBUG    Muxing attempt: 1
09/13/2020 07:56:50 MainProcess     _save_0         ffmpeg          mux_audio                 DEBUG    ffmpy runtime error: `C:\Users\Anshaj\Anaconda3\envs\faceswap\Library\bin\ffmpeg.exe -hide_banner -nostats -v 0 -y -i "D:\aa Faceswap MODELS\outpu\__tmp_seta_converted.mp4" -i "D:\aa Faceswap MODELS\seta.mp4" -map 0:v:0 -map 1:a:0 -c: copy "D:\aa Faceswap MODELS\outpu\seta_converted.mp4"` exited with status 1\n\nSTDOUT:\n\n\nSTDERR:\n
09/13/2020 07:56:50 MainProcess     _save_0         ffmpeg          mux_audio                 DEBUG    Muxing attempt: 2
09/13/2020 07:56:50 MainProcess     _save_0         ffmpeg          mux_audio                 DEBUG    ffmpy runtime error: `C:\Users\Anshaj\Anaconda3\envs\faceswap\Library\bin\ffmpeg.exe -hide_banner -nostats -v 0 -y -i "D:\aa Faceswap MODELS\outpu\__tmp_seta_converted.mp4" -i "D:\aa Faceswap MODELS\seta.mp4" -map 0:v:0 -map 1:a:0 -c: copy "D:\aa Faceswap MODELS\outpu\seta_converted.mp4"` exited with status 1\n\nSTDOUT:\n\n\nSTDERR:\n
09/13/2020 07:56:50 MainProcess     _save_0         ffmpeg          mux_audio                 DEBUG    Muxing attempt: 3
09/13/2020 07:56:50 MainProcess     _save_0         ffmpeg          mux_audio                 DEBUG    ffmpy runtime error: `C:\Users\Anshaj\Anaconda3\envs\faceswap\Library\bin\ffmpeg.exe -hide_banner -nostats -v 0 -y -i "D:\aa Faceswap MODELS\outpu\__tmp_seta_converted.mp4" -i "D:\aa Faceswap MODELS\seta.mp4" -map 0:v:0 -map 1:a:0 -c: copy "D:\aa Faceswap MODELS\outpu\seta_converted.mp4"` exited with status 1\n\nSTDOUT:\n\n\nSTDERR:\n
09/13/2020 07:56:50 MainProcess     _save_0         ffmpeg          mux_audio                 DEBUG    Muxing attempt: 4
09/13/2020 07:56:50 MainProcess     _save_0         ffmpeg          mux_audio                 DEBUG    ffmpy runtime error: `C:\Users\Anshaj\Anaconda3\envs\faceswap\Library\bin\ffmpeg.exe -hide_banner -nostats -v 0 -y -i "D:\aa Faceswap MODELS\outpu\__tmp_seta_converted.mp4" -i "D:\aa Faceswap MODELS\seta.mp4" -map 0:v:0 -map 1:a:0 -c: copy "D:\aa Faceswap MODELS\outpu\seta_converted.mp4"` exited with status 1\n\nSTDOUT:\n\n\nSTDERR:\n
09/13/2020 07:56:50 MainProcess     _save_0         ffmpeg          mux_audio                 DEBUG    Muxing attempt: 5
09/13/2020 07:56:50 MainProcess     _save_0         ffmpeg          mux_audio                 DEBUG    ffmpy runtime error: `C:\Users\Anshaj\Anaconda3\envs\faceswap\Library\bin\ffmpeg.exe -hide_banner -nostats -v 0 -y -i "D:\aa Faceswap MODELS\outpu\__tmp_seta_converted.mp4" -i "D:\aa Faceswap MODELS\seta.mp4" -map 0:v:0 -map 1:a:0 -c: copy "D:\aa Faceswap MODELS\outpu\seta_converted.mp4"` exited with status 1\n\nSTDOUT:\n\n\nSTDERR:\n
09/13/2020 07:56:50 MainProcess     _save_0         ffmpeg          mux_audio                 ERROR    There was a problem muxing audio. The output video has been created but you will need to mux audio yourself either with the EFFMpeg tool or an external application.
09/13/2020 07:56:50 MainProcess     _save_0         ffmpeg          video_file                DEBUG    D:\aa Faceswap MODELS\outpu\seta_converted.mp4
09/13/2020 07:56:50 MainProcess     _save_0         ffmpeg          video_tmp_file            DEBUG    D:\aa Faceswap MODELS\outpu\__tmp_seta_converted.mp4
09/13/2020 07:56:50 MainProcess     _save_0         ffmpeg          video_file                DEBUG    D:\aa Faceswap MODELS\outpu\seta_converted.mp4
09/13/2020 07:56:50 MainProcess     _save_0         multithreading  run                       DEBUG    Error in thread (_save_0): [WinError 2] The system cannot find the file specified: 'D:\\aa Faceswap MODELS\\outpu\\__tmp_seta_converted.mp4' -> 'D:\\aa Faceswap MODELS\\outpu\\seta_converted.mp4'
09/13/2020 07:56:50 MainProcess     MainThread      multithreading  check_and_raise_error     DEBUG    Thread error caught: [(<class 'FileNotFoundError'>, FileNotFoundError(2, 'The system cannot find the file specified'), <traceback object at 0x0000029DF8FDA080>)]
Traceback (most recent call last):
  File "D:\ai faceswap\faceswap\plugins\convert\writer\ffmpeg.py", line 175, in mux_audio
    ffm.run()
  File "C:\Users\Anshaj\Anaconda3\envs\faceswap\lib\site-packages\ffmpy.py", line 105, in run
    raise FFRuntimeError(self.cmd, self.process.returncode, out[0], out[1])
ffmpy.FFRuntimeError: `C:\Users\Anshaj\Anaconda3\envs\faceswap\Library\bin\ffmpeg.exe -hide_banner -nostats -v 0 -y -i "D:\aa Faceswap MODELS\outpu\__tmp_seta_converted.mp4" -i "D:\aa Faceswap MODELS\seta.mp4" -map 0:v:0 -map 1:a:0 -c: copy "D:\aa Faceswap MODELS\outpu\seta_converted.mp4"` exited with status 1

STDOUT:


STDERR:


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\ai faceswap\faceswap\lib\cli\launcher.py", line 156, in execute_script
    process.process()
  File "D:\ai faceswap\faceswap\scripts\convert.py", line 155, in process
    self._convert_images()
  File "D:\ai faceswap\faceswap\scripts\convert.py", line 182, in _convert_images
    self._check_thread_error()
  File "D:\ai faceswap\faceswap\scripts\convert.py", line 202, in _check_thread_error
    thread.check_and_raise_error()
  File "D:\ai faceswap\faceswap\lib\multithreading.py", line 84, in check_and_raise_error
    raise error[1].with_traceback(error[2])
  File "D:\ai faceswap\faceswap\lib\multithreading.py", line 37, in run
    self._target(*self._args, **self._kwargs)
  File "D:\ai faceswap\faceswap\scripts\convert.py", line 627, in _save
    self._writer.close()
  File "D:\ai faceswap\faceswap\plugins\convert\writer\ffmpeg.py", line 141, in close
    self.mux_audio()
  File "D:\ai faceswap\faceswap\plugins\convert\writer\ffmpeg.py", line 183, in mux_audio
    os.rename(self.video_tmp_file, self.video_file)
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'D:\\aa Faceswap MODELS\\outpu\\__tmp_seta_converted.mp4' -> 'D:\\aa Faceswap MODELS\\outpu\\seta_converted.mp4'

============ System Information ============
encoding:            cp1252
git_branch:          master
git_commits:         e6d62b8 Bugfixes:   - dfl_h128 Legacy Weights update   - lib.faces_detect - Logging fix
gpu_cuda:            No global version found. Check Conda packages for Conda Cuda
gpu_cudnn:           No global version found. Check Conda packages for Conda cuDNN
gpu_devices:         GPU_0: Advanced Micro Devices, Inc. - Ellesmere (experimental), GPU_1: Advanced Micro Devices, Inc. - Ellesmere (supported)
gpu_devices_active:  GPU_0, GPU_1
gpu_driver:          ['2841.19', '2841.19']
gpu_vram:            GPU_0: 8192MB, GPU_1: 8192MB
os_machine:          AMD64
os_platform:         Windows-10-10.0.18362-SP0
os_release:          10
py_command:          D:\ai faceswap\faceswap\faceswap.py convert -i D:/aa Faceswap MODELS/output -o D:/aa Faceswap MODELS/outpu -al D:/aa Faceswap MODELS/seta_alignments.fsa -ref D:/aa Faceswap MODELS/seta.mp4 -m D:/aa Faceswap MODELS/model a-b -c avg-color -M none -sc sharpen -w ffmpeg -osc 100 -l 0.4 -j 0 -L INFO -gui
py_conda_version:    conda 4.8.4
py_implementation:   CPython
py_version:          3.8.5
py_virtual_env:      True
sys_cores:           12
sys_processor:       AMD64 Family 23 Model 113 Stepping 0, AuthenticAMD
sys_ram:             Total: 16320MB, Available: 7381MB, Used: 8938MB, Free: 7381MB

=============== Pip Packages ===============
absl-py==0.10.0
astunparse==1.6.3
cachetools==4.1.1
certifi==2020.6.20
cffi==1.14.2
chardet==3.0.4
cycler==0.10.0
enum34==1.1.10
fastcluster==1.1.26
ffmpy==0.2.3
gast==0.3.3
google-auth==1.21.0
google-auth-oauthlib==0.4.1
google-pasta==0.2.0
grpcio==1.31.0
h5py==2.10.0
idna==2.10
imageio @ file:///tmp/build/80754af9/imageio_1594161405741/work
imageio-ffmpeg @ file:///home/conda/feedstock_root/build_artifacts/imageio-ffmpeg_1589202782679/work
joblib @ file:///tmp/build/80754af9/joblib_1594236160679/work
Keras==2.2.4
Keras-Applications==1.0.8
Keras-Preprocessing==1.1.2
kiwisolver==1.2.0
Markdown==3.2.2
matplotlib @ file:///C:/ci/matplotlib-base_1592837548929/work
mkl-fft==1.1.0
mkl-random==1.1.1
mkl-service==2.3.0
numpy @ file:///C:/ci/numpy_and_numpy_base_1596215850360/work
nvidia-ml-py3 @ git+https://github.com/deepfakes/nvidia-ml-py3.git@6fc29ac84b32bad877f078cb4a777c1548a00bf6
oauthlib==3.1.0
olefile==0.46
opencv-python==4.4.0.42
opt-einsum==3.3.0
pathlib==1.0.1
Pillow @ file:///C:/ci/pillow_1594298230227/work
plaidml==0.7.0
plaidml-keras==0.7.0
protobuf==3.13.0
psutil @ file:///C:/ci/psutil_1598370330503/work
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycparser==2.20
pyparsing==2.4.7
python-dateutil==2.8.1
pywin32==227
PyYAML==5.3.1
requests==2.24.0
requests-oauthlib==1.3.0
rsa==4.6
scikit-learn @ file:///C:/ci/scikit-learn_1598377018496/work
scipy==1.4.1
sip==4.19.13
six==1.15.0
tensorboard==2.2.2
tensorboard-plugin-wit==1.7.0
tensorflow==2.2.0
tensorflow-estimator==2.2.0
termcolor==1.1.0
threadpoolctl @ file:///tmp/tmp9twdgx9k/threadpoolctl-2.1.0-py3-none-any.whl
tornado==6.0.4
tqdm @ file:///tmp/build/80754af9/tqdm_1596810128862/work
urllib3==1.25.10
Werkzeug==1.0.1
wincertstore==0.2
wrapt==1.12.1

============== Conda Packages ==============
# packages in environment at C:\Users\Anshaj\Anaconda3\envs\faceswap:
#
# Name                    Version                   Build  Channel
absl-py                   0.10.0                   pypi_0    pypi
astunparse                1.6.3                    pypi_0    pypi
blas                      1.0                         mkl  
ca-certificates           2020.7.22                     0  
cachetools                4.1.1                    pypi_0    pypi
certifi                   2020.6.20                py38_0  
cffi                      1.14.2                   pypi_0    pypi
chardet                   3.0.4                    pypi_0    pypi
cycler                    0.10.0                   py38_0  
enum34                    1.1.10                   pypi_0    pypi
fastcluster               1.1.26           py38hbe40bda_1    conda-forge
ffmpeg                    4.3.1                ha925a31_0    conda-forge
ffmpy                     0.2.3                    pypi_0    pypi
freetype                  2.10.2               hd328e21_0  
gast                      0.3.3                    pypi_0    pypi
git                       2.23.0               h6bb4b03_0  
google-auth               1.21.0                   pypi_0    pypi
google-auth-oauthlib      0.4.1                    pypi_0    pypi
google-pasta              0.2.0                    pypi_0    pypi
grpcio                    1.31.0                   pypi_0    pypi
h5py                      2.10.0                   pypi_0    pypi
icc_rt                    2019.0.0             h0cc432a_1  
icu                       58.2                 ha925a31_3  
idna                      2.10                     pypi_0    pypi
imageio                   2.9.0                      py_0  
imageio-ffmpeg            0.4.2                      py_0    conda-forge
intel-openmp              2020.2                      254  
joblib                    0.16.0                     py_0  
jpeg                      9b                   hb83a4c4_2  
keras                     2.2.4                    pypi_0    pypi
keras-applications        1.0.8                    pypi_0    pypi
keras-preprocessing       1.1.2                    pypi_0    pypi
kiwisolver                1.2.0            py38h74a9793_0  
libpng                    1.6.37               h2a8f88b_0  
libtiff                   4.1.0                h56a325e_1  
lz4-c                     1.9.2                h62dcd97_1  
markdown                  3.2.2                    pypi_0    pypi
matplotlib                3.2.2                         0  
matplotlib-base           3.2.2            py38h64f37c6_0  
mkl                       2020.2                      256  
mkl-service               2.3.0            py38hb782905_0  
mkl_fft                   1.1.0            py38h45dec08_0  
mkl_random                1.1.1            py38h47e9c7a_0  
numpy                     1.19.1           py38h5510c5b_0  
numpy-base                1.19.1           py38ha3acd2a_0  
nvidia-ml-py3             7.352.1                  pypi_0    pypi
oauthlib                  3.1.0                    pypi_0    pypi
olefile                   0.46                       py_0  
opencv-python             4.4.0.42                 pypi_0    pypi
openssl                   1.1.1g               he774522_1  
opt-einsum                3.3.0                    pypi_0    pypi
pathlib                   1.0.1                      py_1  
pillow                    7.2.0            py38hcc1f983_0  
pip                       20.2.2                   py38_0  
plaidml                   0.7.0                    pypi_0    pypi
plaidml-keras             0.7.0                    pypi_0    pypi
protobuf                  3.13.0                   pypi_0    pypi
psutil                    5.7.2            py38he774522_0  
pyasn1                    0.4.8                    pypi_0    pypi
pyasn1-modules            0.2.8                    pypi_0    pypi
pycparser                 2.20                     pypi_0    pypi
pyparsing                 2.4.7                      py_0  
pyqt                      5.9.2            py38ha925a31_4  
python                    3.8.5                he1778fa_0  
python-dateutil           2.8.1                      py_0  
python_abi                3.8                      1_cp38    conda-forge
pywin32                   227              py38he774522_1  
pyyaml                    5.3.1                    pypi_0    pypi
qt                        5.9.7            vc14h73c81de_0  
requests                  2.24.0                   pypi_0    pypi
requests-oauthlib         1.3.0                    pypi_0    pypi
rsa                       4.6                      pypi_0    pypi
scikit-learn              0.23.2           py38h47e9c7a_0  
scipy                     1.4.1                    pypi_0    pypi
setuptools                49.6.0                   py38_0  
sip                       4.19.13          py38ha925a31_0  
six                       1.15.0                     py_0  
sqlite                    3.33.0               h2a8f88b_0  
tensorboard               2.2.2                    pypi_0    pypi
tensorboard-plugin-wit    1.7.0                    pypi_0    pypi
tensorflow                2.2.0                    pypi_0    pypi
tensorflow-estimator      2.2.0                    pypi_0    pypi
termcolor                 1.1.0                    pypi_0    pypi
threadpoolctl             2.1.0              pyh5ca1d4c_0  
tk                        8.6.10               he774522_0  
tornado                   6.0.4            py38he774522_1  
tqdm                      4.48.2                     py_0  
urllib3                   1.25.10                  pypi_0    pypi
vc                        14.1                 h0510ff6_4  
vs2015_runtime            14.16.27012          hf0eaf9b_3  
werkzeug                  1.0.1                    pypi_0    pypi
wheel                     0.35.1                     py_0  
wincertstore              0.2                      py38_0  
wrapt                     1.12.1                   pypi_0    pypi
xz                        5.2.5                h62dcd97_0  
zlib                      1.2.11               h62dcd97_4  
zstd                      1.4.5                h04227a9_0  

================= Configs ==================
--------- .faceswap ---------
backend:                  amd

--------- convert.ini ---------

[color.color_transfer]
clip:                     True
preserve_paper:           True

[color.manual_balance]
colorspace:               HSV
balance_1:                0.0
balance_2:                0.0
balance_3:                0.0
contrast:                 0.0
brightness:               0.0

[color.match_hist]
threshold:                99.0

[mask.box_blend]
type:                     gaussian
distance:                 11.0
radius:                   5.0
passes:                   1

[mask.mask_blend]
type:                     normalized
kernel_size:              3
passes:                   4
threshold:                4
erosion:                  0.0

[scaling.sharpen]
method:                   unsharp_mask
amount:                   150
radius:                   0.3
threshold:                5.0

[writer.ffmpeg]
container:                mp4
codec:                    libx264
crf:                      23
preset:                   medium
tune:                     none
profile:                  auto
level:                    auto
skip_mux:                 False

[writer.gif]
fps:                      25
loop:                     0
palettesize:              256
subrectangles:            False

[writer.opencv]
format:                   png
draw_transparent:         False
jpg_quality:              75
png_compress_level:       3

[writer.pillow]
format:                   png
draw_transparent:         False
optimize:                 False
gif_interlace:            True
jpg_quality:              75
png_compress_level:       3
tif_compression:          tiff_deflate

--------- extract.ini ---------

[global]
allow_growth:             False

[align.fan]
batch-size:               12

[detect.cv2_dnn]
confidence:               50

[detect.mtcnn]
minsize:                  20
threshold_1:              0.6
threshold_2:              0.7
threshold_3:              0.7
scalefactor:              0.709
batch-size:               8

[detect.s3fd]
confidence:               70
batch-size:               4

[mask.unet_dfl]
batch-size:               8

[mask.vgg_clear]
batch-size:               6

[mask.vgg_obstructed]
batch-size:               2

--------- gui.ini ---------

[global]
fullscreen:               False
tab:                      extract
options_panel_width:      30
console_panel_height:     20
icon_size:                14
font:                     default
font_size:                9
autosave_last_session:    prompt
timeout:                  120
auto_load_model_stats:    True

--------- train.ini ---------

[global]
coverage:                 68.75
icnr_init:                False
conv_aware_init:          False
optimizer:                adam
learning_rate:            5e-05
reflect_padding:          False
allow_growth:             False
mixed_precision:          False
convert_batchsize:        16

[global.loss]
loss_function:            ssim
mask_loss_function:       mse
l2_reg_term:              100
eye_multiplier:           12
mouth_multiplier:         8
penalized_mask_loss:      True
mask_type:                extended
mask_blur_kernel:         3
mask_threshold:           4
learn_mask:               False

[model.dfl_h128]
lowmem:                   False

[model.dfl_sae]
input_size:               128
clipnorm:                 True
architecture:             df
autoencoder_dims:         0
encoder_dims:             42
decoder_dims:             21
multiscale_decoder:       False

[model.dlight]
features:                 best
details:                  good
output_size:              256

[model.original]
lowmem:                   False

[model.realface]
input_size:               64
output_size:              128
dense_nodes:              1536
complexity_encoder:       128
complexity_decoder:       512

[model.unbalanced]
input_size:               128
lowmem:                   False
clipnorm:                 True
nodes:                    1024
complexity_encoder:       128
complexity_decoder_a:     384
complexity_decoder_b:     512

[model.villain]
lowmem:                   False

[trainer.original]
preview_images:           14
zoom_amount:              5
rotation_range:           10
shift_range:              5
flip_chance:              50
color_lightness:          30
color_ab:                 8
color_clahe_chance:       50
color_clahe_max_size:     4
```
[crash_report.2020.09.13.080913931075.log](https://github.com/deepfakes/faceswap/files/5213568/crash_report.2020.09.13.080913931075.log)

**Comment by torzdf** [comment] 2020-09-26 23:38
This is an error which only seems to happen on Windows, and I haven't found the cause of it.

**Comment by administratorssssssss** [comment] 2022-02-25 08:57
![image](https://user-images.githubusercontent.com/34373295/155685498-47e7a48d-bb68-4c75-be76-84dbfc5e9a51.png)
What's the reason at this time?

**Comment by torzdf** [comment] 2022-06-30 10:04
Closing issue as method for creating video output has changed.

**Closed by torzdf** 2022-06-30 10:04 UTC
Labels: bug
