### ISSUE TITLE
how do i run my code on CPU? do i need import gpu stats in my code?

### ISSUE THREAD

**Issue by haarissiddiqie1** [deepfakes/faceswap#527] opened 2018-10-24 21:23 UTC
Sorry I know its more of a usability question. I do not have GPU or nvidia. I am running on CPU, so do I need to alter the code at all? There is references to "import GPU stats" etc and of course i get an error message. Any help would be much appreciated.

## Expected behavior

*Describe, in some detail, what you are trying to do and what the output is that you expect from the program.*

## Actual behavior

*Describe, in some detail, what the program does instead. Be sure to include any error message or screenshots.*

## Steps to reproduce

*Describe, in some detail, the steps you tried that resulted in the behavior described above.*

## Other relevant information
- **Command lined used (if not specified in steps to reproduce)**: faceswap.py ...
- **Operating system and version:** Windows, macOS, Linux 
- **Python version:** 2.7, 3.5, 3.6.4, ...
- **Faceswap version:** commit hash or version number
- **Faceswap method:** CPU/GPU
- **Other related issues:** #123, #124...
- ... (for example, installed packages that you can see with `pip freeze`)

**Comment by torzdf** [comment] 2018-10-26 08:09
Duplicate of #518 

Also see: https://github.com/deepfakes/faceswap-playground/issues/164

**Closed by torzdf** 2018-10-26 08:09 UTC

**Comment by haarissiddiqie1** [comment] 2018-10-26 11:02
@torzdf HI there can you help please! i am running the extract python command on CPU (I dont have GPU). And am receiving the following message:
![capture](https://user-images.githubusercontent.com/33531280/47562608-f9e76700-d916-11e8-8d7c-2ea206315e32.PNG)

**Comment by Tvde1** [comment] 2018-10-26 11:04
```
pip install -r requirements.txt
```
Make sure to install all the requirements.
