### ISSUE TITLE
do not extract 

### ISSUE THREAD

**Issue by willshion** [deepfakes/faceswap#789] opened 2019-07-10 15:31 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
![捕获](https://user-images.githubusercontent.com/13349979/60982457-be88ad80-a36a-11e9-9e14-99eebb0c1c29.PNG)

**Smartphone (please complete the following information):**

**Additional context**

**Comment by willshion** [comment] 2019-07-10 15:31
win10 installer

**Comment by willshion** [comment] 2019-07-10 15:31
cant extract

**Comment by torzdf** [comment] 2019-07-10 22:46
It can take a few minutes to launch on the first run as it needs to cache files.

**Comment by willshion** [comment] 2019-07-11 08:29
![捕获](https://user-images.githubusercontent.com/13349979/61035094-1a9a1300-a3f9-11e9-9315-c057c6b8f4b3.PNG)

**Comment by willshion** [comment] 2019-07-11 08:30
1h last not work

**Comment by willshion** [comment] 2019-07-11 08:30
helpme

**Comment by willshion** [comment] 2019-07-11 12:20
![007uWeI8ly1g4v2ayoklmj309t0eywjo](https://user-images.githubusercontent.com/13349979/61050278-3b726080-a419-11e9-8cca-aaf7cad3920e.jpg)
mimi

**Comment by torzdf** [comment] 2019-07-11 17:29
This is a problem with your setup, not with the repo, so I am closing the issue. You are welcome to look for help in the discord server. In the meantime, uninstall your drivers with DDU and re-install from Nvidia site.

**Closed by torzdf** 2019-07-11 17:29 UTC

**Comment by FlamesoFF** [comment] 2019-07-22 12:54
@torzdf No, it's a problem with your installator.
Same issue here - extraction doesn't work after installing through this installator: https://github.com/deepfakes/faceswap/releases with admin privileges enabled.

**Comment by torzdf** [comment] 2019-07-22 15:00
It isn't a problem with the installer. Please don't bump closed threads which have nothing to do with the issue.

If you want to see what the installer does, look at it's source code. The fact that it works for 99% of people means that, in all likelihood, the problem is with their setup, not with the installer.

**Comment by FlamesoFF** [comment] 2019-07-22 21:44
@torzdf Where do you get this info about the "fact" `99% of people`? Most of the people who can't make it work simply forget about it, and only those few part who cares - make topics at bugtracker.

**Comment by torzdf** [comment] 2019-07-22 22:14
The 100s of happy users on our Discord Server.

**Comment by willshion** [comment] 2019-07-24 13:06
iseeeeeeeeeeeeeeeee
isee iseeisee iseeisee iseeisee iseeisee iseeisee iseeisee iseeisee i see 
IT IS NOT SUPPORT FLV  FORMAT!!!!!!!!!!!!!!!!!!!!
IT IS NOT SUPPORT FLV  FORMAT!!!!!!!!!!!!!!!!!!!!
IT IS NOT SUPPORT FLV  FORMAT!!!!!!!!!!!!!!!!!!!!
IT IS NOT SUPPORT FLV  FORMAT!!!!!!!!!!!!!!!!!!!!

**Comment by FlamesoFF** [comment] 2019-08-06 06:50
@torzdf I reinstalled everything in Conda and after pulling latest changes it has finally started to work.
