### ISSUE TITLE
Crash at the end of extraction

### ISSUE THREAD

**Issue by Kirin-kun** [deepfakes/faceswap#454] opened 2018-07-01 12:15 UTC
Environment: Windows 7, GTX 1060 6Gb.

I don't know which commit provoked it, but now, whenever I extract faces, the python.exe crashes with a windows error at the end of the process.

Like, it writes the alignments.json, writes "Done!" and then crashes.

No harm done in the end, but I suspect it's when it unloads some modules. 

Training and conversion work fine.

pip freeze:

absl-py==0.2.2
astor==0.6.2
bleach==1.5.0
click==6.7
cloudpickle==0.5.3
cmake==3.11.0
cycler==0.10.0
dask==0.18.1
decorator==4.3.0
dlib==19.13.1
face-recognition==1.2.2
face-recognition-models==0.3.0
ffmpy==0.2.2
gast==0.2.0
grpcio==1.13.0
h5py==2.8.0
html5lib==0.9999999
Keras==2.2.0
Keras-Applications==1.0.2
Keras-Preprocessing==1.0.1
kiwisolver==1.0.1
Markdown==2.6.11
matplotlib==2.2.2
networkx==2.1
numpy==1.14.5
opencv-python==3.4.1.15
pathlib==1.0.1
Pillow==5.1.0
protobuf==3.6.0
pyparsing==2.2.0
python-dateutil==2.7.3
pytz==2018.5
PyWavelets==0.5.2
PyYAML==3.12
scandir==1.7
scikit-image==0.14.0
scipy==1.1.0
six==1.11.0
tensorboard==1.8.0
tensorflow-gpu==1.8.0
tensorflow-tensorboard==1.5.1
termcolor==1.1.0
toolz==0.9.0
tqdm==4.23.4
Werkzeug==0.14.1

![image](https://user-images.githubusercontent.com/36699120/42134325-d9c95066-7d39-11e8-8d8d-528461125bfb.png)

**Comment by torzdf** [comment] 2018-07-01 13:10
Try the version in staging and see if it still happens. Extract got refactored, with MTCNN added, so if it fixes your issue, this can be closed.

**Comment by Kirin-kun** [comment] 2018-07-01 14:10
staging doesn't work.

For some reason, it stops at the first picture in the folder. I tried with all extractors: same results.
```

(faceenv) C:\Users\Kirin\faceswap>python c:\users\kirin\faceswap\faceswap.py ext
ract -i H:\Fakes\rachel -o H:\Fakes\rachel\aligned -D mtcnn
Using TensorFlow backend.
Output Directory: H:\Fakes\rachel\aligned
Input Directory: H:\Fakes\rachel
Loading Extract from Extract_Align plugin...
Using json serializer
Alignments filepath: H:\Fakes\rachel\alignments.json
Starting, this may take a while...
  0%|                                                   | 0/64 [00:00<?, ?it/s]
Writing alignments to: H:\Fakes\rachel\alignments.json
-------------------------
Images found:        64
Faces detected:      1
-------------------------
Done!
```
The  1 face detected is actually the one in the first picture in the directory.

Whereas, in master, with the same pictures, it works, no problem (except the crash at the end):

```
(faceenv) C:\Users\Kirin\faceswap>python c:\users\kirin\faceswap\faceswap.py ext
ract -i H:\Fakes\rachel -o H:\Fakes\rachel\aligned -D cnn
Using TensorFlow backend.
Output Directory: H:\Fakes\rachel\aligned
Input Directory: H:\Fakes\rachel
Loading Extract from Extract_Align plugin...
Using json serializer
Alignments filepath: H:\Fakes\rachel\alignments.json
Starting, this may take a while...
  0%|                                                   | 0/64 [00:00<?, ?it/s]I
nfo: initializing keras model...
100%|██████████████████████████████████████████| 64/64 [00:36<00:00,  1.76it/s]
Writing alignments to: H:\Fakes\rachel\alignments.json
-------------------------
Images found:        64
Faces detected:      52
-------------------------
Done!
```

**Comment by torzdf** [comment] 2018-07-01 17:06
That's because I'm an idiot and left a line of testing code in. Sorry about that! Re-pull and try again

**Comment by Kirin-kun** [comment] 2018-07-01 18:01
Okay, it works now.

Though, after testing, I must say the mtcnn detector has a lot of problems. It finds faces where there's none and some easy to find faces (that even hog found) are not found/replaced by weird frames containing the whole body, but tilted.

I have a hunch this mtcnn extractor stops when it thinks it has found a single face, even if it's a false positive, when actually there was a real simple-to-find face just a few pixels away.

I don't know how the implementations of mtcnn extractor differ, but the one made by Iperov is better. 

Detected by faceswap mtcnn:
![450290_04big_0](https://user-images.githubusercontent.com/36699120/42137144-b0610b3c-7d67-11e8-8f0a-f128eb48450d.jpg)

Detected by Deepfaceswap mtcnn:
![450290_04big_0](https://user-images.githubusercontent.com/36699120/42137155-c336ba0e-7d67-11e8-9b5f-e10f8091f2e9.png)

I know it's edge case because of the hair, but still...

**Comment by torzdf** [comment] 2018-07-01 22:32
The implementation should be exactly the same. MTCNN is MTCNN it detects faces. It definitely detects more than one face in an image (easy enough to verify),

The only difference from a quick scan of Iperov's code is that he has hardcoded the parameters, whilst I have allowed them to be adjustable by the user, and left them at default.

FWIW, Iperov has amended them to:
mtcnn-minsize - 80.64 (actually calculated by multiplaying scale factor by 0.042. See below)
mtcnn-threshold - 0.7 0.85 0.6
mtcnn-scalefactor - 0.95

Iperov's code also resizes ALL images that go through extraction, regardless of size, to fit to1920px along their longest edge (1850px for dlib). The implementation in faceswap only sizes an image DOWN using the best scaling algorithm available if VRAM is at a premium and it is required. An image will never be upscaled.

I'm not passing judgement on whether one way or the other is better, but my preference is only to resize an image if it needs to be resized... and if it must then to use INTER_AREA interpolation for downsizing.

**Comment by Kirin-kun** [comment] 2018-07-02 07:29
A picture is worth a thousand words. So, explain this:

[R1.zip](https://github.com/deepfakes/faceswap/files/2154192/R1.zip)

Two pics (mostly SFW). These faces are REALLY easy to detect. Even hog is able to. I used all 4 extractors (dlib-cnn, dlib-hog, mtcnn-faceswap, mtcnn-iperov).

But the mtcnn faceswap (aligned.mtcnn directory) was the only one unable to find the faces. It only found the patterns on the dress -_-;

That's why I think there's a problem somewhere.

**Comment by torzdf** [comment] 2018-07-02 07:53
Thanks for this, it's useful. I'll take a look

**Comment by torzdf** [comment] 2018-07-02 08:47
There was a bug which actually affected all detectors (only generating alignments in the last face in all the faces it found). 

This has now been squashed in latest commit. I have tested against your dataset and it seems to work as intended, albeit, you get 2 false positives along with the 2 faces. You should be able to eliminate this by tweaking settings (specifically minsize. I found that setting this to 100 eliminated the false positives in your images).

Obviously this value is specific to the images that are being fed in.

**Comment by Kirin-kun** [comment] 2018-07-02 08:53
I'll close this one and test. If there's other problems. I'll report.

**Comment by Kirin-kun** [comment] 2018-07-02 09:14
It's better now.

I still have that case, where Deepfacelab works, but faceswap fails (both with mtcnn):

[R2.zip](https://github.com/deepfakes/faceswap/files/2154570/R2.zip)

Difference in the rescaling of the image?

**Comment by torzdf** [comment] 2018-07-02 09:43
I'm going to look into this. The bounding box comes out of mtcnn correctly `rectangle(296,164,428,378)`, but somewhere in face-alignment it goes wrong

**Comment by torzdf** [comment] 2018-07-03 08:39
Ok, the reason this happens is that whilst the face is detected correctly, the fact that the face is mainly obscured means that the landmark detection goes screwy and places most of the landmarks in the wrong place.

These landmarks are then used to align the images, and the process expects a certain landmark layout. The fact that they are all over the place leads to a strange image alignment.

To illustrate, the highlighted landmarks below should be along the jawline:
![image](https://user-images.githubusercontent.com/36920800/42208750-da4db02e-7ea4-11e8-8cd0-e59355b2a2aa.png)


As you can see, they clearly aren't!

As this is edge case, it is not a priority to look into fixing this, so I am closing this issue. As always, unobscured faces will always work best.

**Closed by torzdf** 2018-07-03 08:39 UTC

**Comment by Kirin-kun** [comment] 2018-07-03 09:17
Well, DeepFaceLab finds relatively correct landmarks along the jawline with mtcnn and produces a valid aligned face upon extraction:

![450290_04big_debug](https://user-images.githubusercontent.com/36699120/42210717-020d1962-7eb2-11e8-8207-98e7e5870728.png)

![image](https://user-images.githubusercontent.com/36699120/42210786-2dcc70fc-7eb2-11e8-8eca-27d97dab6764.png)

It must be doing something different to achieve its result.

Maybe the upscaling.
