### ISSUE TITLE
ERROR    Caught exception in thread: 'training_0'

### ISSUE THREAD

**Issue by changyunke** [deepfakes/faceswap#630] opened 2019-02-27 11:59 UTC
When i run this bot on ubuntu1604 to train the model, some problem were happened. Installing different versions of tensorflow won't work either. I have no idea to solve it. whether professor can give some suggestions? The problem are as follows:
 

Using TensorFlow backend.
02/27/2019 19:36:19 INFO     Model A Directory: /home/csy/Documents/faceswap/data/trump
02/27/2019 19:36:19 INFO     Model B Directory: /home/csy/Documents/faceswap/data/cage
02/27/2019 19:36:19 INFO     Training data directory: /home/csy/Documents/faceswap/models
02/27/2019 19:36:19 INFO     ===============================================
02/27/2019 19:36:19 INFO     - Starting                                    -
02/27/2019 19:36:19 INFO     - Press 'ENTER' to save and quit              -
02/27/2019 19:36:19 INFO     - Press 'S' to save model weights immediately -
02/27/2019 19:36:19 INFO     ===============================================
02/27/2019 19:36:20 INFO     Loading data, this may take a while...
02/27/2019 19:36:20 INFO     Loading Model from Original plugin...
02/27/2019 19:36:23 INFO     Loading config: '/home/csy/Documents/faceswap/config/train.ini'
02/27/2019 19:36:23 WARNING  No existing state file found. Generating.
02/27/2019 19:36:23 WARNING  Failed loading existing training data. Generating new models
02/27/2019 19:36:23 INFO     Loading Trainer from Original plugin...
02/27/2019 19:36:24 INFO     Enabled TensorBoard Logging
02/27/2019 19:36:26 CRITICAL Error caught! Exiting...
02/27/2019 19:36:26 ERROR    Caught exception in thread: 'training_0'
You are using pip version 10.0.1, however version 19.0.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
02/27/2019 19:36:29 ERROR    Got Exception on main handler:
Traceback (most recent call last):
  File "/home/csy/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1323, in _do_call
    return fn(*args)
  File "/home/csy/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1302, in _run_fn
    status, run_metadata)
  File "/home/csy/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.FailedPreconditionError: Attempting to use uninitialized value Adam/iterations
	 [[Node: Adam/iterations/read = Identity[T=DT_INT64, _class=["loc:@Adam/iterations"], _device="/job:localhost/replica:0/task:0/device:CPU:0"](Adam/iterations)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/csy/Documents/faceswap/lib/cli.py", line 90, in execute_script
    process.process()
  File "/home/csy/Documents/faceswap/scripts/train.py", line 97, in process
    self.end_thread(thread, err)
  File "/home/csy/Documents/faceswap/scripts/train.py", line 122, in end_thread
    thread.join()
  File "/home/csy/Documents/faceswap/lib/multithreading.py", line 179, in join
    raise thread.err[1].with_traceback(thread.err[2])
  File "/home/csy/Documents/faceswap/lib/multithreading.py", line 117, in run
    self._target(*self._args, **self._kwargs)
  File "/home/csy/Documents/faceswap/scripts/train.py", line 148, in training
    raise err
  File "/home/csy/Documents/faceswap/scripts/train.py", line 138, in training
    self.run_training_cycle(model, trainer)
  File "/home/csy/Documents/faceswap/scripts/train.py", line 210, in run_training_cycle
    trainer.train_one_step(viewer, timelapse)
  File "/home/csy/Documents/faceswap/plugins/train/trainer/_base.py", line 138, in train_one_step
    loss[side] = batcher.train_one_batch(is_preview_iteration)
  File "/home/csy/Documents/faceswap/plugins/train/trainer/_base.py", line 212, in train_one_batch
    loss = self.model.predictors[self.side].train_on_batch(*batch)
  File "/home/csy/anaconda3/lib/python3.6/site-packages/keras/engine/training.py", line 1217, in train_on_batch
    outputs = self.train_function(ins)
  File "/home/csy/anaconda3/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 2721, in __call__
    return self._legacy_call(inputs)
  File "/home/csy/anaconda3/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 2693, in _legacy_call
    **self.session_kwargs)
  File "/home/csy/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 889, in run
    run_metadata_ptr)
  File "/home/csy/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1120, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/csy/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1317, in _do_run
    options, run_metadata)
  File "/home/csy/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1336, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.FailedPreconditionError: Attempting to use uninitialized value Adam/iterations
	 [[Node: Adam/iterations/read = Identity[T=DT_INT64, _class=["loc:@Adam/iterations"], _device="/job:localhost/replica:0/task:0/device:CPU:0"](Adam/iterations)]]

Caused by op 'Adam/iterations/read', defined at:
  File "/home/csy/anaconda3/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
  File "/home/csy/anaconda3/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/csy/Documents/faceswap/lib/multithreading.py", line 117, in run
    self._target(*self._args, **self._kwargs)
  File "/home/csy/Documents/faceswap/scripts/train.py", line 136, in training
    model = self.load_model()
  File "/home/csy/Documents/faceswap/scripts/train.py", line 162, in load_model
    preview_scale=self.args.preview_scale)
  File "/home/csy/Documents/faceswap/plugins/train/model/original.py", line 24, in __init__
    super().__init__(*args, **kwargs)
  File "/home/csy/Documents/faceswap/plugins/train/model/_base.py", line 75, in __init__
    self.build()
  File "/home/csy/Documents/faceswap/plugins/train/model/_base.py", line 124, in build
    self.compile_predictors()
  File "/home/csy/Documents/faceswap/plugins/train/model/_base.py", line 202, in compile_predictors
    optimizer = Adam(lr=5e-5, beta_1=0.5, beta_2=0.999, clipnorm=1.0)
  File "/home/csy/anaconda3/lib/python3.6/site-packages/keras/optimizers.py", line 462, in __init__
    self.iterations = K.variable(0, dtype='int64', name='iterations')
  File "/home/csy/anaconda3/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 402, in variable
    v = tf.Variable(value, dtype=tf.as_dtype(dtype), name=name)
  File "/home/csy/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/variables.py", line 213, in __init__
    constraint=constraint)
  File "/home/csy/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/variables.py", line 356, in _init_from_args
    self._snapshot = array_ops.identity(self._variable, name="read")
  File "/home/csy/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py", line 125, in identity
    return gen_array_ops.identity(input, name=name)
  File "/home/csy/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py", line 2071, in identity
    "Identity", input=input, name=name)
  File "/home/csy/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/csy/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2956, in create_op
    op_def=op_def)
  File "/home/csy/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1470, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

FailedPreconditionError (see above for traceback): Attempting to use uninitialized value Adam/iterations
	 [[Node: Adam/iterations/read = Identity[T=DT_INT64, _class=["loc:@Adam/iterations"], _device="/job:localhost/replica:0/task:0/device:CPU:0"](Adam/iterations)]]

02/27/2019 19:36:29 CRITICAL An unexpected crash has occurred. Crash report written to /home/csy/Documents/faceswap/crash_report.2019.02.27.193626340426.log. Please verify you are running the latest version of faceswap before reporting
terminate called without an active exception
Aborted (core dumped)
      Running environment  are:
       python 3.6
       cuda 8
      cudnn 6
     tensorflow-gpu 1.4.0
    how can i fix this.                                            
                         thank you.

**Comment by torzdf** [comment] 2019-02-27 12:03
Duplicate of #629
Duplicate of #626

**Closed** 2019-02-27 12:03 UTC
