### ISSUE TITLE
 No GPU detected,switch to cpu mode

### ISSUE THREAD

**Issue by saltfishh** [deepfakes/faceswap#1116] opened 2021-01-09 07:46 UTC
it shows me `no gpu detected,switch to cpu mode`when i extract from a video.

My step:

1. setup faceswap,and i selected amd mode.
2. setup environment,open anaconda-navigator
3. extract from video in gui mode.

here is my host env:

- OS
  - archlinux x86, Kernel: 5.10.5-arch1-1 
- CPU
  -  amd 3600,GPU: xfx amd rx590
- python version
  - 3.8

- conda version
  - 4.9.2

- here is terminal output context:
  >Loading...
Setting Faceswap backend to AMD
No GPU detected. Switching to CPU mode
01/09/2021 15:21:21 INFO     Log level set to: INFO
01/09/2021 15:21:21 WARNING  No GPU detected. Switching to CPU mode
01/09/2021 15:21:21 INFO     Switching backend to CPU. Using Tensorflow for CPU operations.
01/09/2021 15:21:22 INFO     Output Directory: /home/wind/Project/faceswap-workdir/faces/putin
01/09/2021 15:21:22 WARNING  No GPU detected. Switching to CPU mode
01/09/2021 15:21:22 INFO     Loading Detect from S3Fd plugin...
01/09/2021 15:21:22 INFO     Loading Align from Fan plugin...
01/09/2021 15:21:22 INFO     Loading Mask from Components plugin...
01/09/2021 15:21:22 INFO     Loading Mask from Extended plugin...
01/09/2021 15:21:22 INFO     Loading Mask from Vgg_Obstructed plugin...
01/09/2021 15:21:22 INFO     Downloading model: 'Nirkin_500_softmax' from: https://github.com/deepfakes-models/faceswap-models/releases/download/v1.5.1/Nirkin_500_softmax_v1.zip
01/09/2021 15:22:48 INFO     Extracting: 'Nirkin_500_softmax'
01/09/2021 15:22:50 INFO     Starting, this may take a while...
01/09/2021 15:22:50 INFO     Initializing S3FD (Detect)...
01/09/2021 15:22:50 INFO     Initialized S3FD (Detect) with batchsize of 4

this is my screenshot:

![2021-01-09_15-36](https://user-images.githubusercontent.com/44364154/104086299-a1030f80-5291-11eb-804f-f41454bf0863.png)

**Comment by torzdf** [comment] 2021-01-09 18:55
Please post output of Help>Output System Informaton

**Comment by saltfishh** [comment] 2021-01-10 02:54
> Please post output of Help>Output System Informaton

thanks for reply
hereis my output context of  `help==>output system inf`

>============ System Information ============
encoding:            UTF-8
git_branch:          位于分支 master
git_commits:         f9a5b72 Bugfix - setup.py. Explicitly install cudatoolkit in Conda. b1420a6 Merge pull request #1096 from deepfakes/dev-tf2.4. 29667b4 Expand support for tf2.2-2.4. 3438198 Merge branch 'master' into dev-tf2.4. b67f91e travis test typo fix
gpu_cuda:            No global version found. Check Conda packages for Conda Cuda
gpu_cudnn:           No global version found. Check Conda packages for Conda cuDNN
gpu_devices:         
gpu_devices_active:  
gpu_driver:          []
gpu_vram:            
os_machine:          x86_64
os_platform:         Linux-5.10.5-arch1-1-x86_64-with-glibc2.10
os_release:          5.10.5-arch1-1
py_command:          faceswap.py gui
py_conda_version:    conda 4.9.2
py_implementation:   CPython
py_version:          3.8.5
py_virtual_env:      True
sys_cores:           12
sys_processor:       
sys_ram:             Total: 16018MB, Available: 6479MB, Used: 8838MB, Free: 2343MB

> =============== Pip Packages ===============
absl-py @ file:///tmp/build/80754af9/absl-py_1607439979954/work
aiohttp @ file:///tmp/build/80754af9/aiohttp_1602530294624/work
astunparse==1.6.3
async-timeout==3.0.1
attrs @ file:///tmp/build/80754af9/attrs_1604765588209/work
blinker==1.4
brotlipy==0.7.0
cachetools @ file:///tmp/build/80754af9/cachetools_1607706694405/work
certifi==2020.12.5
cffi @ file:///tmp/build/80754af9/cffi_1606255081583/work
chardet @ file:///tmp/build/80754af9/chardet_1605303185383/work
click==7.1.2
cryptography @ file:///tmp/build/80754af9/cryptography_1607635341180/work
cycler==0.10.0
enum34==1.1.10
fastcluster==1.1.26
ffmpy==0.2.3
gast==0.3.3
google-auth @ file:///tmp/build/80754af9/google-auth_1607969906642/work
google-auth-oauthlib @ file:///tmp/build/80754af9/google-auth-oauthlib_1603929124518/work
google-pasta==0.2.0
grpcio @ file:///tmp/build/80754af9/grpcio_1597424474635/work
h5py @ file:///tmp/build/80754af9/h5py_1593454122442/work
idna @ file:///tmp/build/80754af9/idna_1593446292537/work
imageio @ file:///tmp/build/80754af9/imageio_1594161405741/work
imageio-ffmpeg @ file:///home/conda/feedstock_root/build_artifacts/imageio-ffmpeg_1609799311556/work
importlib-metadata @ file:///tmp/build/80754af9/importlib-metadata_1602276842396/work
joblib @ file:///tmp/build/80754af9/joblib_1607970656719/work
Keras==2.2.4
Keras-Applications==1.0.8
Keras-Preprocessing==1.1.0
kiwisolver @ file:///tmp/build/80754af9/kiwisolver_1604014535162/work
Markdown @ file:///tmp/build/80754af9/markdown_1605111056890/work
matplotlib @ file:///tmp/build/80754af9/matplotlib-base_1592846008246/work
mkl-fft==1.2.0
mkl-random==1.1.1
mkl-service==2.3.0
multidict @ file:///tmp/build/80754af9/multidict_1600456399709/work
numpy @ file:///tmp/build/80754af9/numpy_and_numpy_base_1603570489231/work
nvidia-ml-py3 @ git+https://github.com/deepfakes/nvidia-ml-py3.git@6fc29ac84b32bad877f078cb4a777c1548a00bf6
oauthlib==3.1.0
olefile==0.46
opencv-python==4.5.1.48
opt-einsum==3.1.0
pathlib==1.0.1
Pillow @ file:///tmp/build/80754af9/pillow_1609786786540/work
plaidml==0.7.0
plaidml-keras==0.7.0
protobuf==3.13.0
psutil @ file:///tmp/build/80754af9/psutil_1598370257551/work
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycparser @ file:///tmp/build/80754af9/pycparser_1594388511720/work
PyJWT==1.7.1
pyOpenSSL @ file:///tmp/build/80754af9/pyopenssl_1608057966937/work
pyparsing==2.4.7
PySocks @ file:///tmp/build/80754af9/pysocks_1605305779399/work
python-dateutil==2.8.1
PyYAML==5.3.1
requests @ file:///tmp/build/80754af9/requests_1608241421344/work
requests-oauthlib==1.3.0
rsa @ file:///tmp/build/80754af9/rsa_1596998415516/work
scikit-learn @ file:///tmp/build/80754af9/scikit-learn_1598376899566/work
scipy==1.4.1
sip==4.19.13
six @ file:///tmp/build/80754af9/six_1605205327372/work
tensorboard==2.2.2
tensorboard-plugin-wit==1.6.0
tensorflow==2.2.0
tensorflow-estimator==2.2.0
termcolor==1.1.0
threadpoolctl @ file:///tmp/tmp9twdgx9k/threadpoolctl-2.1.0-py3-none-any.whl
tornado @ file:///tmp/build/80754af9/tornado_1606942300299/work
tqdm @ file:///tmp/build/80754af9/tqdm_1609788246169/work
urllib3 @ file:///tmp/build/80754af9/urllib3_1606938623459/work
Werkzeug==1.0.1
wrapt==1.12.1
yarl @ file:///tmp/build/80754af9/yarl_1606939922162/work
zipp @ file:///tmp/build/80754af9/zipp_1604001098328/work

> ============== Conda Packages ==============
> #packages in environment at /home/wind/Project/anaconda3/envs/faceswap:
> #
> #Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_tflow_select             2.3.0                       mkl  
absl-py                   0.11.0             pyhd3eb1b0_1  
aiohttp                   3.6.3            py38h7b6447c_0  
astunparse                1.6.3                      py_0  
async-timeout             3.0.1                    py38_0  
attrs                     20.3.0             pyhd3eb1b0_0  
blas                      1.0                         mkl  
blinker                   1.4                      py38_0  
brotlipy                  0.7.0           py38h27cfd23_1003  
bzip2                     1.0.8                h516909a_3    conda-forge
c-ares                    1.17.1               h27cfd23_0  
ca-certificates           2020.12.8            h06a4308_0  
cachetools                4.2.0              pyhd3eb1b0_0  
certifi                   2020.12.5        py38h06a4308_0  
cffi                      1.14.4           py38h261ae71_0  
chardet                   3.0.4           py38h06a4308_1003  
click                     7.1.2                      py_0  
cryptography              3.3.1            py38h3c74f83_0  
cycler                    0.10.0                   py38_0  
dbus                      1.13.18              hb2f20db_0  
enum34                    1.1.10                   pypi_0    pypi
expat                     2.2.10               he6710b0_2  
fastcluster               1.1.26           py38hc5bc63f_2    conda-forge
ffmpeg                    4.3.1                h3215721_1    conda-forge
ffmpy                     0.2.3                    pypi_0    pypi
fontconfig                2.13.0               h9420a91_0  
freetype                  2.10.4               h5ab3b9f_0  
gast                      0.3.3                      py_0  
glib                      2.66.1               h92f7085_0  
gmp                       6.2.1                h58526e2_0    conda-forge
gnutls                    3.6.13               h85f3911_1    conda-forge
google-auth               1.24.0             pyhd3eb1b0_0  
google-auth-oauthlib      0.4.2              pyhd3eb1b0_2  
google-pasta              0.2.0                      py_0  
grpcio                    1.31.0           py38hf8bcb03_0  
gst-plugins-base          1.14.0               h8213a91_2  
gstreamer                 1.14.0               h28cd5cc_2  
h5py                      2.10.0           py38hd6299e0_1  
hdf5                      1.10.6               hb1b8bf9_0  
icu                       58.2                 he6710b0_3  
idna                      2.10                       py_0  
imageio                   2.9.0                      py_0  
imageio-ffmpeg            0.4.3              pyhd8ed1ab_0    conda-forge
importlib-metadata        2.0.0                      py_1  
intel-openmp              2020.2                      254  
joblib                    1.0.0              pyhd3eb1b0_0  
jpeg                      9b                   h024ee3a_2  
keras                     2.2.4                    pypi_0    pypi
keras-applications        1.0.8                    pypi_0    pypi
keras-preprocessing       1.1.0                      py_1  
kiwisolver                1.3.0            py38h2531618_0  
lame                      3.100             h14c3975_1001    conda-forge
lcms2                     2.11                 h396b838_0  
ld_impl_linux-64          2.33.1               h53a641e_7  
libedit                   3.1.20191231         h14c3975_1  
libffi                    3.3                  he6710b0_2  
libgcc-ng                 9.1.0                hdf63c60_0  
libgfortran-ng            7.3.0                hdf63c60_0  
libiconv                  1.16                 h516909a_0    conda-forge
libpng                    1.6.37               hbc83047_0  
libprotobuf               3.13.0.1             hd408876_0  
libstdcxx-ng              9.1.0                hdf63c60_0  
libtiff                   4.1.0                h2733197_1  
libuuid                   1.0.3                h1bed415_2  
libxcb                    1.14                 h7b6447c_0  
libxml2                   2.9.10               hb55368b_3  
lz4-c                     1.9.2                heb0550a_3  
markdown                  3.3.3            py38h06a4308_0  
matplotlib                3.2.2                         0  
matplotlib-base           3.2.2            py38hef1b27d_0  
mkl                       2020.2                      256  
mkl-service               2.3.0            py38he904b0f_0  
mkl_fft                   1.2.0            py38h23d657b_0  
mkl_random                1.1.1            py38h0573a6f_0  
multidict                 4.7.6            py38h7b6447c_1  
ncurses                   6.2                  he6710b0_1  
nettle                    3.6                  he412f7d_0    conda-forge
numpy                     1.19.2           py38h54aff64_0  
numpy-base                1.19.2           py38hfa32c7d_0  
nvidia-ml-py3             7.352.1                  pypi_0    pypi
oauthlib                  3.1.0                      py_0  
olefile                   0.46                       py_0  
opencv-python             4.5.1.48                 pypi_0    pypi
openh264                  2.1.1                h8b12597_0    conda-forge
openssl                   1.1.1i               h27cfd23_0  
opt_einsum                3.1.0                      py_0  
pathlib                   1.0.1                      py_1  
pcre                      8.44                 he6710b0_0  
pillow                    8.1.0            py38he98fc37_0  
pip                       20.3.3           py38h06a4308_0  
plaidml                   0.7.0                    pypi_0    pypi
plaidml-keras             0.7.0                    pypi_0    pypi
protobuf                  3.13.0.1         py38he6710b0_1  
psutil                    5.7.2            py38h7b6447c_0  
pyasn1                    0.4.8                      py_0  
pyasn1-modules            0.2.8                      py_0  
pycparser                 2.20                       py_2  
pyjwt                     1.7.1                    py38_0  
pyopenssl                 20.0.1             pyhd3eb1b0_1  
pyparsing                 2.4.7                      py_0  
pyqt                      5.9.2            py38h05f1152_4  
pysocks                   1.7.1            py38h06a4308_0  
python                    3.8.5                h7579374_1  
python-dateutil           2.8.1                      py_0  
python_abi                3.8                      1_cp38    conda-forge
pyyaml                    5.3.1                    pypi_0    pypi
qt                        5.9.7                h5867ecd_1  
readline                  8.0                  h7b6447c_0  
requests                  2.25.1             pyhd3eb1b0_0  
requests-oauthlib         1.3.0                      py_0  
rsa                       4.6                        py_0  
scikit-learn              0.23.2           py38h0573a6f_0  
scipy                     1.4.1                    pypi_0    pypi
setuptools                51.0.0           py38h06a4308_2  
sip                       4.19.13          py38he6710b0_0  
six                       1.15.0           py38h06a4308_0  
sqlite                    3.33.0               h62c20be_0  
tensorboard               2.2.2                    pypi_0    pypi
tensorboard-plugin-wit    1.6.0                      py_0  
tensorflow                2.2.0           mkl_py38h6d3daf0_0  
tensorflow-base           2.2.0           mkl_py38h5059a2d_0  
tensorflow-estimator      2.2.0              pyh208ff02_0  
termcolor                 1.1.0                    py38_1  
threadpoolctl             2.1.0              pyh5ca1d4c_0  
tk                        8.6.10               hbc83047_0  
tornado                   6.1              py38h27cfd23_0  
tqdm                      4.55.1             pyhd3eb1b0_0  
urllib3                   1.26.2             pyhd3eb1b0_0  
werkzeug                  1.0.1                      py_0  
wheel                     0.36.2             pyhd3eb1b0_0  
wrapt                     1.12.1           py38h7b6447c_1  
x264                      1!152.20180806       h14c3975_0    conda-forge
xz                        5.2.5                h7b6447c_0  
yarl                      1.6.3            py38h27cfd23_0  
zipp                      3.4.0              pyhd3eb1b0_0  
zlib                      1.2.11               h7b6447c_3  
zstd                      1.4.5                h9ceee32_0  

> ================= Configs ==================
> --------- gui.ini ---------

> [global]
fullscreen:               False
tab:                      extract
options_panel_width:      30
console_panel_height:     20
icon_size:                14
font:                     default
font_size:                9
autosave_last_session:    prompt
timeout:                  120
auto_load_model_stats:    True

> --------- train.ini ---------

> [global]
centering:                face
coverage:                 68.75
icnr_init:                False
conv_aware_init:          False
optimizer:                adam
learning_rate:            5e-05
reflect_padding:          False
allow_growth:             False
mixed_precision:          False
convert_batchsize:        16

> [global.loss]
loss_function:            ssim
mask_loss_function:       mse
l2_reg_term:              100
eye_multiplier:           3
mouth_multiplier:         2
penalized_mask_loss:      True
mask_type:                extended
mask_blur_kernel:         3
mask_threshold:           4
learn_mask:               False

> [model.unbalanced]
input_size:               128
lowmem:                   False
clipnorm:                 True
nodes:                    1024
complexity_encoder:       128
complexity_decoder_a:     384
complexity_decoder_b:     512

> [model.dfaker]
output_size:              128

> [model.dlight]
features:                 best
details:                  good
output_size:              256

>[model.dfl_h128]
lowmem:                   False

> [model.villain]
lowmem:                   False

> [model.dfl_sae]
input_size:               128
clipnorm:                 True
architecture:             df
autoencoder_dims:         0
encoder_dims:             42
decoder_dims:             21
multiscale_decoder:       False

> [model.realface]
input_size:               64
output_size:              128
dense_nodes:              1536
complexity_encoder:       128
complexity_decoder:       512

> [model.original]
lowmem:                   False

> [trainer.original]
preview_images:           14
zoom_amount:              5
rotation_range:           10
shift_range:              5
flip_chance:              50
disable_warp:             False
color_lightness:          30
color_ab:                 8
color_clahe_chance:       50
color_clahe_max_size:     4

> --------- extract.ini ---------

> [global]
allow_growth:             False

> [detect.mtcnn]
minsize:                  20
threshold_1:              0.6
threshold_2:              0.7
threshold_3:              0.7
scalefactor:              0.709
batch-size:               8

> [detect.cv2_dnn]
confidence:               50

> [detect.s3fd]
confidence:               70
batch-size:               4

> [mask.vgg_clear]
batch-size:               6

> [mask.unet_dfl]
batch-size:               8

> [mask.vgg_obstructed]
batch-size:               2

> [align.fan]
batch-size:               12

> --------- convert.ini ---------

 > [scaling.sharpen]
method:                   none
amount:                   150
radius:                   0.3
threshold:                5.0

> [mask.mask_blend]
type:                     normalized
kernel_size:              3
passes:                   4
threshold:                4
erosion:                  0.0

> [mask.box_blend]
type:                     gaussian
distance:                 11.0
radius:                   5.0
passes:                   1

> [writer.gif]
fps:                      25
loop:                     0
palettesize:              256
subrectangles:            False

> [writer.opencv]
format:                   png
draw_transparent:         False
jpg_quality:              75
png_compress_level:       3

> [writer.pillow]
format:                   png
draw_transparent:         False
optimize:                 False
gif_interlace:            True
jpg_quality:              75
png_compress_level:       3
tif_compression:          tiff_deflate

> [writer.ffmpeg]
container:                mp4
codec:                    libx264
crf:                      23
preset:                   medium
tune:                     none
profile:                  auto
level:                    auto
skip_mux:                 False

> [color.manual_balance]
colorspace:               HSV
balance_1:                0.0
balance_2:                0.0
balance_3:                0.0
contrast:                 0.0
brightness:               0.0

> [color.color_transfer]
clip:                     True
preserve_paper:           True

> [color.match_hist]
threshold:                99.0

> --------- .faceswap ---------
backend:                  amd

that's all .thanks!

**Comment by torzdf** [comment] 2021-01-10 12:07
The issue is that your GPU driver is not detected.

For AMD on Linux, the AMDGPU PRO drivers must be used. I do not know the nuances of getting the correct components on Arch, but hopefully this helps:
https://wiki.archlinux.org/index.php/AMDGPU_PRO

I'm closing this issue as it is not a bug in FS. If you need further help getting this working, then our [forum](https://faceswap.dev/forum) or [Discord](https://discord.gg/FC54sYg) will probably serve you better as other AMD users can hopefully help out.

**Closed by torzdf** 2021-01-10 12:07 UTC

**Comment by saltfishh** [comment] 2021-01-10 12:11
thanks for ur help,i'll try ur guid.thanks
