### ISSUE TITLE
Training error

### ISSUE THREAD

**Issue by callmejm** [deepfakes/faceswap#1199] opened 2021-12-22 08:30 UTC
I getting below error while training
```
Exception in Tkinter callback
TypeError: float() argument must be a string or a number, not 'list'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Marvel\MiniConda3\envs\faceswap\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "C:\Users\Marvel\faceswap\lib\gui\display_analysis.py", line 114, in _update_current_session
    self._reset_session()
  File "C:\Users\Marvel\faceswap\lib\gui\display_analysis.py", line 270, in _reset_session
    self._set_session_summary("Currently running training session")
  File "C:\Users\Marvel\faceswap\lib\gui\display_analysis.py", line 196, in _set_session_summary
    result = self._thread.get_result()
  File "C:\Users\Marvel\faceswap\lib\gui\utils.py", line 1230, in get_result
    raise self.err[1].with_traceback(self.err[2])
  File "C:\Users\Marvel\faceswap\lib\gui\utils.py", line 1201, in run
    retval = self._target(*self._args, **self._kwargs)
  File "C:\Users\Marvel\faceswap\lib\gui\display_analysis.py", line 215, in _summarise_data
    return session.full_summary
  File "C:\Users\Marvel\faceswap\lib\gui\analysis\stats.py", line 72, in full_summary
    return self._summary.get_summary_stats()
  File "C:\Users\Marvel\faceswap\lib\gui\analysis\stats.py", line 287, in get_summary_stats
    self._get_time_stats()
  File "C:\Users\Marvel\faceswap\lib\gui\analysis\stats.py", line 319, in _get_time_stats
    latest = self._session.get_timestamps(session_id)
  File "C:\Users\Marvel\faceswap\lib\gui\analysis\stats.py", line 209, in get_timestamps
    retval = self._tb_logs.get_timestamps(session_id=session_id)
  File "C:\Users\Marvel\faceswap\lib\gui\analysis\event_reader.py", line 498, in get_timestamps
    self._check_cache(idx)
  File "C:\Users\Marvel\faceswap\lib\gui\analysis\event_reader.py", line 442, in _check_cache
    self._cache_data(session_id)
  File "C:\Users\Marvel\faceswap\lib\gui\analysis\event_reader.py", line 428, in _cache_data
    parser.cache_events(session_id)
  File "C:\Users\Marvel\faceswap\lib\gui\analysis\event_reader.py", line 584, in cache_events
    self._cache.cache_data(session_id, data, self._loss_labels, is_live=self._live_data)
  File "C:\Users\Marvel\faceswap\lib\gui\analysis\event_reader.py", line 169, in cache_data
    timestamps, loss = self._to_numpy(data, is_live)
  File "C:\Users\Marvel\faceswap\lib\gui\analysis\event_reader.py", line 210, in _to_numpy
    times, loss = (np.array(times, dtype="float64"), np.array(loss, dtype="float32"))
ValueError: setting an array element with a sequence.
12/22/2021 16:26:32 INFO     [Saved models] - Average loss since last save: face_a: 0.01576, face_b: 0.01913
```

**Comment by bryanlyon** [comment] 2021-12-22 17:29
Duplicate of #1159

**Closed by bryanlyon** 2021-12-22 17:29 UTC
