### ISSUE TITLE
How to use effmpeg?

### ISSUE THREAD

**Issue by scarecrow2415** [deepfakes/faceswap#447] opened 2018-06-25 06:47 UTC
when I push 'effmpeg' button, this happen.

Loading...
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\kwg20\AppData\Local\Programs\Python\Python36\lib\tkinter\__init__.py", line 1702, in __call__
    return self.func(*args)
  File "C:\faceswap\lib\gui\wrapper.py", line 66, in action_command
    self.task.execute_script(command, args)
  File "C:\faceswap\lib\gui\wrapper.py", line 156, in execute_script
    kwargs["preexec_fn"] = os.setsid
AttributeError: module 'os' has no attribute 'setsid'
Terminating Process Group...
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\kwg20\AppData\Local\Programs\Python\Python36\lib\tkinter\__init__.py", line 1702, in __call__
    return self.func(*args)
  File "C:\faceswap\lib\gui\wrapper.py", line 62, in action_command
    self.task.terminate()
  File "C:\faceswap\lib\gui\wrapper.py", line 275, in terminate
    pgid = os.getpgid(self.process.pid)
AttributeError: module 'os' has no attribute 'getpgid'

**Comment by torzdf** [comment] 2018-06-25 08:14
#445

**Comment by scarecrow2415** [comment] 2018-06-25 11:12
OS Version: Windows 10
command generated: python C:\faceswap\tools.py effmpeg -a extract -i input -fps -1.0 -ef .png -s 00:00:00 -e 00:00:00 -d 00:00:00 -sc 1920x1080
pip-freeze: C:\Users\kwg20>pip freeze
absl-py==0.2.2
astor==0.6.2
bleach==1.5.0
click==6.7
cloudpickle==0.5.3
cmake==3.11.0
cycler==0.10.0
dask==0.18.0
decorator==4.3.0
dlib==19.13.1
face-recognition==1.2.2
face-recognition-models==0.3.0
ffmpy==0.2.2
gast==0.2.0
grpcio==1.12.1
h5py==2.8.0
html5lib==0.9999999
Keras==2.2.0
Keras-Applications==1.0.2
Keras-Preprocessing==1.0.1
kiwisolver==1.0.1
Markdown==2.6.11
matplotlib==2.2.2
networkx==2.1
numpy==1.14.5
opencv-python==3.4.1.15
pathlib==1.0.1
Pillow==5.1.0
protobuf==3.6.0
pyparsing==2.2.0
python-dateutil==2.7.3
pytz==2018.4
PyWavelets==0.5.2
PyYAML==3.12
scandir==1.7
scikit-image==0.14.0
scipy==1.1.0
six==1.11.0
tensorboard==1.8.0
tensorflow-gpu==1.5.0
tensorflow-tensorboard==1.5.1
termcolor==1.1.0
toolz==0.9.0
tqdm==4.23.4
Werkzeug==0.14.1

**Comment by torzdf** [comment] 2018-06-25 12:33
Thanks for the feedback. Effmpeg for the gui is in alpha/beta at the moment. We will look at this as soon as we can.

**Comment by torzdf** [comment] 2018-07-09 09:02
duplicate of #445

**Comment by torzdf** [comment] 2018-07-09 09:02
Duplicate of #445

**Closed** 2018-07-09 09:02 UTC
