### ISSUE TITLE
CUDNN_STATUS_ALLOC_FAILED

### ISSUE THREAD

**Issue by Aki113s** [deepfakes/faceswap#798] opened 2019-07-18 15:03 UTC
**Describe the bug**
Critical Error, I got the frames from effmpeg, loaded them into Extract, hit extract and then the error below a few seconds later

**Expected behavior**
Thought Faceswap would begin Extraction

Loading...
07/18/2019 07:52:24 INFO     Log level set to: INFO
07/18/2019 07:52:26 INFO     Output Directory: C:\Users\Philip\Documents\faceswap\Faceswap_NakedGun2_Pt1\Align_for_Training_A
07/18/2019 07:52:26 INFO     Input Directory: C:\Users\Philip\Documents\faceswap\Faceswap_NakedGun2_Pt1\Img_A
07/18/2019 07:52:26 INFO     Loading Detect from S3Fd plugin...
07/18/2019 07:52:26 INFO     Loading Align from Fan plugin...
07/18/2019 07:52:26 INFO     Starting, this may take a while...
07/18/2019 07:52:27 INFO     Initializing S3FD Detector...
2019-07-18 07:52:38.449679: E tensorflow/stream_executor/cuda/cuda_dnn.cc:334] Could not create cudnn handle: CUDNN_STATUS_ALLOC_FAILED
2019-07-18 07:52:38.450371: E tensorflow/stream_executor/cuda/cuda_dnn.cc:334] Could not create cudnn handle: CUDNN_STATUS_ALLOC_FAILED
07/18/2019 07:52:38 ERROR    Caught exception in child process: 21412: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.\n	 [[node s3fd/convolution (defined at C:\Users\Philip\faceswap\plugins\extract\detect\s3fd.py:147) ]]\n	 [[node s3fd/transpose_99 (defined at C:\Users\Philip\faceswap\plugins\extract\detect\s3fd.py:147) ]]\n\nCaused by op 's3fd/convolution', defined at:\n File "<string>", line 1, in <module>\n File "C:\Users\Philip\MiniConda3\envs\faceswap\lib\multiprocessing\spawn.py", line 105, in spawn_main\n exitcode = _main(fd)\n File "C:\Users\Philip\MiniConda3\envs\faceswap\lib\multiprocessing\spawn.py", line 118, in _main\n return self._bootstrap()\n File "C:\Users\Philip\MiniConda3\envs\faceswap\lib\multiprocessing\process.py", line 258, in _bootstrap\n self.run()\n File "C:\Users\Philip\faceswap\lib\multithreading.py", line 361, in run\n super().run()\n File "C:\Users\Philip\MiniConda3\envs\faceswap\lib\multiprocessing\process.py", line 93, in run\n self._target(*self._args, **self._kwargs)\n File "C:\Users\Philip\faceswap\plugins\extract\detect\_base.py", line 129, in run\n self.detect_faces(*args, **kwargs)\n File "C:\Users\Philip\faceswap\plugins\extract\detect\s3fd.py", line 75, in detect_faces\n super().detect_faces(*args, **kwargs)\n File "C:\Users\Philip\faceswap\plugins\extract\detect\_base.py", line 101, in detect_faces\n self.initialize(*args, **kwargs)\n File "C:\Users\Philip\faceswap\plugins\extract\detect\s3fd.py", line 44, in initialize\n self.model = S3fd(self.model_path, self.target, tf_ratio, card_id, confidence)\n File "C:\Users\Philip\faceswap\plugins\extract\detect\s3fd.py", line 132, in __init__\n self.graph = self.load_graph()\n File "C:\Users\Philip\faceswap\plugins\extract\detect\s3fd.py", line 147, in load_graph\n self.tf.import_graph_def(graph_def, name="s3fd")\n File "C:\Users\Philip\MiniConda3\envs\faceswap\lib\site-packages\tensorflow\python\util\deprecation.py", line 507, in new_func\n return func(*args, **kwargs)\n File "C:\Users\Philip\MiniConda3\envs\faceswap\lib\site-packages\tensorflow\python\framework\importer.py", line 442, in import_graph_def\n _ProcessNewOps(graph)\n File "C:\Users\Philip\MiniConda3\envs\faceswap\lib\site-packages\tensorflow\python\framework\importer.py", line 235, in _ProcessNewOps\n for new_op in graph._add_new_tf_operations(compute_devices=False): # pylint: disable=protected-access\n File "C:\Users\Philip\MiniConda3\envs\faceswap\lib\site-packages\tensorflow\python\framework\ops.py", line 3433, in _add_new_tf_operations\n for c_op in c_api_util.new_tf_operations(self)\n File "C:\Users\Philip\MiniConda3\envs\faceswap\lib\site-packages\tensorflow\python\framework\ops.py", line 3433, in <listcomp>\n for c_op in c_api_util.new_tf_operations(self)\n File "C:\Users\Philip\MiniConda3\envs\faceswap\lib\site-packages\tensorflow\python\framework\ops.py", line 3325, in _create_op_from_tf_operation\n ret = Operation(c_op, self)\n File "C:\Users\Philip\MiniConda3\envs\faceswap\lib\site-packages\tensorflow\python\framework\ops.py", line 1801, in __init__\n self._traceback = tf_stack.extract_stack()\n\nUnknownError (see above for traceback): Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.\n	 [[node s3fd/convolution (defined at C:\Users\Philip\faceswap\plugins\extract\detect\s3fd.py:147) ]]\n	 [[node s3fd/transpose_99 (defined at C:\Users\Philip\faceswap\plugins\extract\detect\s3fd.py:147) ]]\n
07/18/2019 07:52:38 ERROR    Traceback:
Traceback (most recent call last):
File "C:\Users\Philip\MiniConda3\envs\faceswap\lib\site-packages\tensorflow\python\client\session.py", line 1334, in _do_call
return fn(*args)
File "C:\Users\Philip\MiniConda3\envs\faceswap\lib\site-packages\tensorflow\python\client\session.py", line 1319, in _run_fn
options, feed_dict, fetch_list, target_list, run_metadata)
File "C:\Users\Philip\MiniConda3\envs\faceswap\lib\site-packages\tensorflow\python\client\session.py", line 1407, in _call_tf_sessionrun
run_metadata)
tensorflow.python.framework.errors_impl.UnknownError: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
[[{{node s3fd/convolution}}]]
[[{{node s3fd/transpose_99}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "C:\Users\Philip\faceswap\plugins\extract\detect\_base.py", line 129, in run
self.detect_faces(*args, **kwargs)
File "C:\Users\Philip\faceswap\plugins\extract\detect\s3fd.py", line 75, in detect_faces
super().detect_faces(*args, **kwargs)
File "C:\Users\Philip\faceswap\plugins\extract\detect\_base.py", line 101, in detect_faces
self.initialize(*args, **kwargs)
File "C:\Users\Philip\faceswap\plugins\extract\detect\s3fd.py", line 71, in initialize
raise err
File "C:\Users\Philip\faceswap\plugins\extract\detect\s3fd.py", line 44, in initialize
self.model = S3fd(self.model_path, self.target, tf_ratio, card_id, confidence)
File "C:\Users\Philip\faceswap\plugins\extract\detect\s3fd.py", line 135, in __init__
self.session = self.set_session(target_size, vram_ratio, card_id)
File "C:\Users\Philip\faceswap\plugins\extract\detect\s3fd.py", line 174, in set_session
session.run(self.output, feed_dict={self.input: placeholder})
File "C:\Users\Philip\MiniConda3\envs\faceswap\lib\site-packages\tensorflow\python\client\session.py", line 929, in run
run_metadata_ptr)
File "C:\Users\Philip\MiniConda3\envs\faceswap\lib\site-packages\tensorflow\python\client\session.py", line 1152, in _run
feed_dict_tensor, options, run_metadata)
File "C:\Users\Philip\MiniConda3\envs\faceswap\lib\site-packages\tensorflow\python\client\session.py", line 1328, in _do_run
run_metadata)
File "C:\Users\Philip\MiniConda3\envs\faceswap\lib\site-packages\tensorflow\python\client\session.py", line 1348, in _do_call
raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.UnknownError: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
[[node s3fd/convolution (defined at C:\Users\Philip\faceswap\plugins\extract\detect\s3fd.py:147) ]]
[[node s3fd/transpose_99 (defined at C:\Users\Philip\faceswap\plugins\extract\detect\s3fd.py:147) ]]

Caused by op 's3fd/convolution', defined at:
File "<string>", line 1, in <module>
File "C:\Users\Philip\MiniConda3\envs\faceswap\lib\multiprocessing\spawn.py", line 105, in spawn_main
exitcode = _main(fd)
File "C:\Users\Philip\MiniConda3\envs\faceswap\lib\multiprocessing\spawn.py", line 118, in _main
return self._bootstrap()
File "C:\Users\Philip\MiniConda3\envs\faceswap\lib\multiprocessing\process.py", line 258, in _bootstrap
self.run()
File "C:\Users\Philip\faceswap\lib\multithreading.py", line 361, in run
super().run()
File "C:\Users\Philip\MiniConda3\envs\faceswap\lib\multiprocessing\process.py", line 93, in run
self._target(*self._args, **self._kwargs)
File "C:\Users\Philip\faceswap\plugins\extract\detect\_base.py", line 129, in run
self.detect_faces(*args, **kwargs)
File "C:\Users\Philip\faceswap\plugins\extract\detect\s3fd.py", line 75, in detect_faces
super().detect_faces(*args, **kwargs)
File "C:\Users\Philip\faceswap\plugins\extract\detect\_base.py", line 101, in detect_faces
self.initialize(*args, **kwargs)
File "C:\Users\Philip\faceswap\plugins\extract\detect\s3fd.py", line 44, in initialize
self.model = S3fd(self.model_path, self.target, tf_ratio, card_id, confidence)
File "C:\Users\Philip\faceswap\plugins\extract\detect\s3fd.py", line 132, in __init__
self.graph = self.load_graph()
File "C:\Users\Philip\faceswap\plugins\extract\detect\s3fd.py", line 147, in load_graph
self.tf.import_graph_def(graph_def, name="s3fd")
File "C:\Users\Philip\MiniConda3\envs\faceswap\lib\site-packages\tensorflow\python\util\deprecation.py", line 507, in new_func
return func(*args, **kwargs)
File "C:\Users\Philip\MiniConda3\envs\faceswap\lib\site-packages\tensorflow\python\framework\importer.py", line 442, in import_graph_def
_ProcessNewOps(graph)
File "C:\Users\Philip\MiniConda3\envs\faceswap\lib\site-packages\tensorflow\python\framework\importer.py", line 235, in _ProcessNewOps
for new_op in graph._add_new_tf_operations(compute_devices=False):  # pylint: disable=protected-access
File "C:\Users\Philip\MiniConda3\envs\faceswap\lib\site-packages\tensorflow\python\framework\ops.py", line 3433, in _add_new_tf_operations
for c_op in c_api_util.new_tf_operations(self)
File "C:\Users\Philip\MiniConda3\envs\faceswap\lib\site-packages\tensorflow\python\framework\ops.py", line 3433, in <listcomp>
for c_op in c_api_util.new_tf_operations(self)
File "C:\Users\Philip\MiniConda3\envs\faceswap\lib\site-packages\tensorflow\python\framework\ops.py", line 3325, in _create_op_from_tf_operation
ret = Operation(c_op, self)
File "C:\Users\Philip\MiniConda3\envs\faceswap\lib\site-packages\tensorflow\python\framework\ops.py", line 1801, in __init__
self._traceback = tf_stack.extract_stack()
UnknownError (see above for traceback): Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
[[node s3fd/convolution (defined at C:\Users\Philip\faceswap\plugins\extract\detect\s3fd.py:147) ]]
[[node s3fd/transpose_99 (defined at C:\Users\Philip\faceswap\plugins\extract\detect\s3fd.py:147) ]]

07/18/2019 07:52:43 ERROR    Got Exception on main handler:
Traceback (most recent call last):
File "C:\Users\Philip\faceswap\lib\cli.py", line 122, in execute_script
process.process()
File "C:\Users\Philip\faceswap\scripts\extract.py", line 61, in process
self.run_extraction()
File "C:\Users\Philip\faceswap\scripts\extract.py", line 181, in run_extraction
self.extractor.launch()
File "C:\Users\Philip\faceswap\plugins\extract\pipeline.py", line 175, in launch
self.launch_detector()
File "C:\Users\Philip\faceswap\plugins\extract\pipeline.py", line 238, in launch_detector
raise ValueError("Error initializing Detector")
ValueError: Error initializing Detector
07/18/2019 07:52:43 CRITICAL An unexpected crash has occurred. Crash report written to 'C:\Users\Philip\faceswap\crash_report.2019.07.18.075243331247.log'. Please verify you are running the latest version of faceswap before reporting
Process exited.

**Desktop (please complete the following information):**
Windows 10
Intel E3 Xeon_v5 Skylake
32gb DDR4
Nvidia RTX 2080

**Additional context**
  File "C:\Users\Philip\MiniConda3\envs\faceswap\lib\site-packages\tensorflow\python\client\session.py", line 1328, in _do_run
    run_metadata)
  File "C:\Users\Philip\MiniConda3\envs\faceswap\lib\site-packages\tensorflow\python\client\session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.UnknownError: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[node s3fd/convolution (defined at C:\Users\Philip\faceswap\plugins\extract\detect\s3fd.py:147) ]]
	 [[node s3fd/transpose_99 (defined at C:\Users\Philip\faceswap\plugins\extract\detect\s3fd.py:147) ]]

Caused by op 's3fd/convolution', defined at:
  File "<string>", line 1, in <module>
  File "C:\Users\Philip\MiniConda3\envs\faceswap\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\Philip\MiniConda3\envs\faceswap\lib\multiprocessing\spawn.py", line 118, in _main
    return self._bootstrap()
  File "C:\Users\Philip\MiniConda3\envs\faceswap\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "C:\Users\Philip\faceswap\lib\multithreading.py", line 361, in run
    super().run()
  File "C:\Users\Philip\MiniConda3\envs\faceswap\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Philip\faceswap\plugins\extract\detect\_base.py", line 129, in run
    self.detect_faces(*args, **kwargs)
  File "C:\Users\Philip\faceswap\plugins\extract\detect\s3fd.py", line 75, in detect_faces
    super().detect_faces(*args, **kwargs)
  File "C:\Users\Philip\faceswap\plugins\extract\detect\_base.py", line 101, in detect_faces
    self.initialize(*args, **kwargs)
  File "C:\Users\Philip\faceswap\plugins\extract\detect\s3fd.py", line 44, in initialize
    self.model = S3fd(self.model_path, self.target, tf_ratio, card_id, confidence)
  File "C:\Users\Philip\faceswap\plugins\extract\detect\s3fd.py", line 132, in __init__
    self.graph = self.load_graph()
  File "C:\Users\Philip\faceswap\plugins\extract\detect\s3fd.py", line 147, in load_graph
    self.tf.import_graph_def(graph_def, name="s3fd")
  File "C:\Users\Philip\MiniConda3\envs\faceswap\lib\site-packages\tensorflow\python\util\deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "C:\Users\Philip\MiniConda3\envs\faceswap\lib\site-packages\tensorflow\python\framework\importer.py", line 442, in import_graph_def
    _ProcessNewOps(graph)
  File "C:\Users\Philip\MiniConda3\envs\faceswap\lib\site-packages\tensorflow\python\framework\importer.py", line 235, in _ProcessNewOps
    for new_op in graph._add_new_tf_operations(compute_devices=False):  # pylint: disable=protected-access
  File "C:\Users\Philip\MiniConda3\envs\faceswap\lib\site-packages\tensorflow\python\framework\ops.py", line 3433, in _add_new_tf_operations
    for c_op in c_api_util.new_tf_operations(self)
  File "C:\Users\Philip\MiniConda3\envs\faceswap\lib\site-packages\tensorflow\python\framework\ops.py", line 3433, in <listcomp>
    for c_op in c_api_util.new_tf_operations(self)
  File "C:\Users\Philip\MiniConda3\envs\faceswap\lib\site-packages\tensorflow\python\framework\ops.py", line 3325, in _create_op_from_tf_operation
    ret = Operation(c_op, self)
  File "C:\Users\Philip\MiniConda3\envs\faceswap\lib\site-packages\tensorflow\python\framework\ops.py", line 1801, in __init__
    self._traceback = tf_stack.extract_stack()

UnknownError (see above for traceback): Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[node s3fd/convolution (defined at C:\Users\Philip\faceswap\plugins\extract\detect\s3fd.py:147) ]]
	 [[node s3fd/transpose_99 (defined at C:\Users\Philip\faceswap\plugins\extract\detect\s3fd.py:147) ]]
Traceback (most recent call last):
  File "C:\Users\Philip\faceswap\lib\cli.py", line 122, in execute_script
    process.process()
  File "C:\Users\Philip\faceswap\scripts\extract.py", line 61, in process
    self.run_extraction()
  File "C:\Users\Philip\faceswap\scripts\extract.py", line 181, in run_extraction
    self.extractor.launch()
  File "C:\Users\Philip\faceswap\plugins\extract\pipeline.py", line 175, in launch
    self.launch_detector()
  File "C:\Users\Philip\faceswap\plugins\extract\pipeline.py", line 238, in launch_detector
    raise ValueError("Error initializing Detector")
ValueError: Error initializing Detector

============ System Information ============
encoding:            cp1252
git_branch:          master
git_commits:         5f73418 Update icons. 0a82e51 Bugflx: Correct input variable to res_block. ae259e9 Add .mpg file extension support. afdf8c8 Image loader Variable name fix. 4371d50 Remove he_uniform from init from res block and use FS default
gpu_cuda:            No global version found. Check Conda packages for Conda Cuda
gpu_cudnn:           No global version found. Check Conda packages for Conda cuDNN
gpu_devices:         GPU_0: GeForce RTX 2080
gpu_devices_active:  GPU_0
gpu_driver:          419.35
gpu_vram:            GPU_0: 8192MB
os_machine:          AMD64
os_platform:         Windows-10-10.0.17763-SP0
os_release:          10
py_command:          C:\Users\Philip\faceswap\faceswap.py extract -i C:/Users/Philip/Documents/faceswap/Faceswap_NakedGun2_Pt1/Img_A -o C:/Users/Philip/Documents/faceswap/Faceswap_NakedGun2_Pt1/Align_for_Training_A -l 0.4 --serializer json -D s3fd -A fan -nm none -bt 0.0 -sz 256 -min 0 -een 10 -si 0 -L INFO -gui
py_conda_version:    conda 4.7.5
py_implementation:   CPython
py_version:          3.6.8
py_virtual_env:      True
sys_cores:           8
sys_processor:       Intel64 Family 6 Model 94 Stepping 3, GenuineIntel
sys_ram:             Total: 32713MB, Available: 21369MB, Used: 11343MB, Free: 21369MB

=============== Pip Packages ===============
absl-py==0.7.1
astor==0.7.1
certifi==2019.6.16
cloudpickle==1.2.1
cycler==0.10.0
cytoolz==0.9.0.1
dask==2.0.0
decorator==4.4.0
fastcluster==1.1.25
ffmpy==0.2.2
gast==0.2.2
grpcio==1.16.1
h5py==2.9.0
imageio==2.5.0
imageio-ffmpeg==0.3.0
joblib==0.13.2
Keras==2.2.4
Keras-Applications==1.0.8
Keras-Preprocessing==1.1.0
kiwisolver==1.1.0
Markdown==3.1.1
matplotlib==2.2.2
mkl-fft==1.0.12
mkl-random==1.0.2
mkl-service==2.0.2
mock==3.0.5
networkx==2.3
numpy==1.16.2
nvidia-ml-py3==7.352.0
olefile==0.46
pathlib==1.0.1
Pillow==6.0.0
protobuf==3.8.0
psutil==5.6.3
pyparsing==2.4.0
pyreadline==2.1
python-dateutil==2.8.0
pytz==2019.1
PyWavelets==1.0.3
pywin32==223
PyYAML==5.1.1
scikit-image==0.15.0
scikit-learn==0.21.2
scipy==1.2.1
six==1.12.0
tensorboard==1.13.1
tensorflow==1.13.1
tensorflow-estimator==1.13.0
termcolor==1.1.0
toolz==0.9.0
toposort==1.5
tornado==6.0.3
tqdm==4.32.1
Werkzeug==0.15.4
wincertstore==0.2

============== Conda Packages ==============
# packages in environment at C:\Users\Philip\MiniConda3\envs\faceswap:
#
# Name                    Version                   Build  Channel
_tflow_select             2.1.0                       gpu  
absl-py                   0.7.1                    py36_0  
astor                     0.7.1                    py36_0  
blas                      1.0                         mkl  
ca-certificates           2019.5.15                     0  
certifi                   2019.6.16                py36_0  
cloudpickle               1.2.1                      py_0  
cudatoolkit               10.0.130                      0  
cudnn                     7.6.0                cuda10.0_0  
cycler                    0.10.0           py36h009560c_0  
cytoolz                   0.9.0.1          py36hfa6e2cd_1  
dask-core                 2.0.0                      py_0  
decorator                 4.4.0                    py36_1  
fastcluster               1.1.25          py36h830ac7b_1000    conda-forge
ffmpeg                    4.1.3                h6538335_0    conda-forge
ffmpy                     0.2.2                    pypi_0    pypi
freetype                  2.9.1                ha9979f8_1  
gast                      0.2.2                    py36_0  
grpcio                    1.16.1           py36h351948d_1  
h5py                      2.9.0            py36h5e291fa_0  
hdf5                      1.10.4               h7ebc959_0  
icc_rt                    2019.0.0             h0cc432a_1  
icu                       58.2                 ha66f8fd_1  
imageio                   2.5.0                    py36_0  
imageio-ffmpeg            0.3.0                      py_0    conda-forge
intel-openmp              2019.4                      245  
joblib                    0.13.2                   py36_0  
jpeg                      9c                hfa6e2cd_1001    conda-forge
keras                     2.2.4                         0  
keras-applications        1.0.8                      py_0  
keras-base                2.2.4                    py36_0  
keras-preprocessing       1.1.0                      py_1  
kiwisolver                1.1.0            py36ha925a31_0  
libblas                   3.8.0                     8_mkl    conda-forge
libcblas                  3.8.0                     8_mkl    conda-forge
liblapack                 3.8.0                     8_mkl    conda-forge
liblapacke                3.8.0                     8_mkl    conda-forge
libmklml                  2019.0.3                      0  
libpng                    1.6.37               h7602738_0    conda-forge
libprotobuf               3.8.0                h7bd577a_0  
libtiff                   4.0.10            h6512ee2_1003    conda-forge
libwebp                   1.0.2                hfa6e2cd_2    conda-forge
lz4-c                     1.8.3             he025d50_1001    conda-forge
markdown                  3.1.1                    py36_0  
matplotlib                2.2.2            py36had4c4a9_2  
mkl                       2019.4                      245  
mkl-service               2.0.2            py36he774522_0  
mkl_fft                   1.0.12           py36h14836fe_0  
mkl_random                1.0.2            py36h343c172_0  
mock                      3.0.5                    py36_0  
networkx                  2.3                        py_0  
numpy                     1.16.2           py36h19fb1c0_0  
numpy-base                1.16.2           py36hc3f5095_0  
nvidia-ml-py3             7.352.0                  pypi_0    pypi
olefile                   0.46                     py36_0  
opencv                    4.1.0            py36hb4945ee_5    conda-forge
openssl                   1.1.1c               he774522_1  
pathlib                   1.0.1                    py36_1  
pillow                    6.0.0            py36hdc69c19_0  
pip                       19.1.1                   py36_0  
protobuf                  3.8.0            py36h33f27b4_0  
psutil                    5.6.3            py36he774522_0  
pyparsing                 2.4.0                      py_0  
pyqt                      5.9.2            py36h6538335_2  
pyreadline                2.1                      py36_1  
python                    3.6.8                h9f7ef89_7  
python-dateutil           2.8.0                    py36_0  
pytz                      2019.1                     py_0  
pywavelets                1.0.3            py36h8c2d366_1  
pywin32                   223              py36hfa6e2cd_1  
pyyaml                    5.1.1            py36he774522_0  
qt                        5.9.7                hc6833c9_1    conda-forge
scikit-image              0.15.0           py36ha925a31_0  
scikit-learn              0.21.2           py36h6288b17_0  
scipy                     1.2.1            py36h29ff71c_0  
setuptools                41.0.1                   py36_0  
sip                       4.19.8           py36h6538335_0  
six                       1.12.0                   py36_0  
sqlite                    3.28.0               he774522_0  
tensorboard               1.13.1           py36h33f27b4_0  
tensorflow                1.13.1          gpu_py36h9006a92_0  
tensorflow-base           1.13.1          gpu_py36h871c8ca_0  
tensorflow-estimator      1.13.0                     py_0  
tensorflow-gpu            1.13.1               h0d30ee6_0  
termcolor                 1.1.0                    py36_1  
tk                        8.6.8                hfa6e2cd_0  
toolz                     0.9.0                    py36_0  
toposort                  1.5                        py_3    conda-forge
tornado                   6.0.3            py36he774522_0  
tqdm                      4.32.1                     py_0  
vc                        14.1                 h0510ff6_4  
vs2015_runtime            14.15.26706          h3a45250_4  
werkzeug                  0.15.4                     py_0  
wheel                     0.33.4                   py36_0  
wincertstore              0.2              py36h7fe50ca_0  
xz                        5.2.4             h2fa13f4_1001    conda-forge
yaml                      0.1.7                hc54c509_2  
zlib                      1.2.11            h2fa13f4_1004    conda-forge
zstd                      1.4.0                hd8a0e53_0    conda-forge

**Comment by torzdf** [comment] 2019-07-18 15:05
We are trying to find the cause of this bug.

If you run with `--single-process` or the `Single Process` flag enabled, it should run.

**Comment by Aki113s** [comment] 2019-07-18 15:20
I did have that engaged, I did just downgrade from s3fd to the other gpu
one and it started to go.

**Comment by SharkEzz** [comment] 2019-08-12 12:19
Any news regarding this issue ? I'm facing the same (but the 'Single Process' workaround worked)

**Comment by torzdf** [comment] 2019-08-12 21:34
I *think* this happens because TF 1.13.1 uses more VRAM, so the amount we allocate for s3fd is not enough. I use TF 1.12 and do not get this issue.

I will probably up the allocation for S3FD at some point, but in the meantime, just use single process.

**Comment by torzdf** [comment] 2019-09-26 16:26
This issue should be fixed in latest commits.

**Closed by torzdf** 2019-09-26 16:26 UTC
