### ISSUE TITLE
Not showing graph in gui

### ISSUE THREAD

**Issue by telecast-git** [deepfakes/faceswap#656] opened 2019-03-09 22:16 UTC
in log gui:
`Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.6/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "/home/telecast/Documents/faceswap/lib/gui/command.py", line 461, in <lambda>
    command=lambda cmd=action: cmd(self.command))
  File "/home/telecast/Documents/faceswap/lib/gui/utils.py", line 550, in load
    self.add_to_recent(cfgfile.name, command)
  File "/home/telecast/Documents/faceswap/lib/gui/utils.py", line 596, in add_to_recent
    recent_files = self.serializer.unmarshal(inp.read().decode("utf-8"))
  File "/home/telecast/Documents/faceswap/lib/Serializer.py", line 61, in unmarshal
    return json.loads(input_string)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
`

 faceswap.log:
`03/10/2019 00:02:36 MainProcess     training_0      train           training                  INFO     Loading data, this may take a while...
03/10/2019 00:02:36 MainProcess     training_0      plugin_loader   _import                   INFO     Loading Model from Villain plugin...
03/10/2019 00:02:40 MainProcess     training_0      config          load_config               INFO     Loading config: '/home/telecast/Documents/faceswap/config/train.ini'
03/10/2019 00:02:40 MainProcess     training_0      _base           replace_config            INFO     Using configuration saved in state file
03/10/2019 00:02:40 MainProcess     training_0      deprecation     new_func                  WARNING  From /home/telecast/Documents/faceswap_env/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.\nInstructions for updating:\nColocations handled automatically by placer.
03/10/2019 00:02:49 MainProcess     training_0      _base           load                      WARNING  Failed loading existing training data. Generating new models
03/10/2019 00:02:52 MainProcess     training_0      plugin_loader   _import                   INFO     Loading Trainer from Original plugin...
03/10/2019 00:02:54 MainProcess     training_0      _base           set_tensorboard           INFO     Enabled TensorBoard Logging
03/10/2019 00:02:54 MainProcess     training_0      deprecation     new_func                  WARNING  From /home/telecast/Documents/faceswap_env/lib/python3.6/site-packages/tensorflow/python/ops/math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.\nInstructions for updating:\nUse tf.cast instead.
03/10/2019 00:03:35 MainProcess     training_0      _base           save_models               INFO     saved models
03/10/2019 00:04:29 MainProcess     MainThread      train           end_thread                INFO     Exit requested! The trainer will complete its current cycle, save the models and quit (it can take up a couple of seconds depending on your training speed). If you want to kill it now, press Ctrl + c
03/10/2019 00:04:31 MainProcess     training_0      _base           save_models               INFO     saved models`

$ cat /etc/*release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.10

$ pip3 list
Package                 Version 
----------------------- --------
absl-py                 0.7.0   
astor                   0.7.1   
Click                   7.0     
cloudpickle             0.8.0   
cmake                   3.13.3  
cycler                  0.10.0  
dask                    1.1.3   
decorator               4.3.2   
dlib                    19.16.0 
face-recognition        1.2.3   
face-recognition-models 0.3.0   
ffmpy                   0.2.2   
gast                    0.2.2   
grpcio                  1.19.0  
h5py                    2.9.0   
Keras                   2.2.4   
Keras-Applications      1.0.7   
Keras-Preprocessing     1.0.9   
kiwisolver              1.0.1   
Markdown                3.0.1   
matplotlib              2.2.2   
mock                    2.0.0   
networkx                2.2     
numpy                   1.15.4  
nvidia-ml-py3           7.352.0 
opencv-python           4.0.0.21
pathlib                 1.0.1   
pbr                     5.1.3   
Pillow                  5.4.1   
pip                     19.0.3  
protobuf                3.7.0   
psutil                  5.6.0   
pyparsing               2.3.1   
python-dateutil         2.8.0   
pytz                    2018.9  
PyWavelets              1.0.2   
PyYAML                  3.13    
scikit-image            0.14.2  
scikit-learn            0.20.3  
scipy                   1.2.1   
setuptools              40.8.0  
six                     1.12.0  
tensorboard             1.13.1  
tensorflow-estimator    1.13.0  
tensorflow-gpu          1.13.1  
termcolor               1.1.0   
toolz                   0.9.0   
tqdm                    4.31.1  
Werkzeug                0.14.1  
wheel                   0.33.1

$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Sat_Aug_25_21:08:01_CDT_2018
Cuda compilation tools, release 10.0, V10.0.130

 cudnn v7.4.1.5

**Comment by torzdf** [comment] 2019-03-10 13:05
Can you confirm whether the following file exists, and if so, could you provide it?
`<faceswap folder>/lib/gui/.cache/.recent.json`

**Comment by telecast-git** [comment] 2019-03-10 16:26
Hi, @torzdf 
thank for your reply!
This file is exist, but it's empty. 
> :~/Documents/faceswap$ ll lib/gui/.cache/.recent.json
-rw-rw-r-- 1 telecast telecast 0 мар  3 16:56 lib/gui/.cache/.recent.json

**Comment by torzdf** [comment] 2019-03-11 13:22
This should be fixed in latest commit

**Comment by telecast-git** [comment] 2019-03-11 14:38
unfortunately the graph is not showing with last commit.
In gui log error:
<pre>
03/11/2019 17:35:05 WARNING  From /home/telecast/Documents/faceswap_env/lib/python3.6/site-packages/tensorflow/python/ops/math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.\nInstructions for updating:\nUse tf.cast instead.

03/11/2019 17:35:31 INFO     saved models
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.6/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "/usr/lib/python3.6/tkinter/__init__.py", line 749, in callit
    func(*args)
  File "/home/telecast/Documents/faceswap/lib/gui/display_page.py", line 245, in <lambda>
    self.after(waittime, lambda t=waittime: self.update_page(t))
  File "/home/telecast/Documents/faceswap/lib/gui/display_page.py", line 244, in update_page
    self.load_display()
  File "/home/telecast/Documents/faceswap/lib/gui/display_page.py", line 256, in load_display
    self.display_item_process()
  File "/home/telecast/Documents/faceswap/lib/gui/display_command.py", line 217, in display_item_process
    selections=["raw", "trend"])
  File "/home/telecast/Documents/faceswap/lib/gui/stats.py", line 348, in __init__
    self.refresh()
  File "/home/telecast/Documents/faceswap/lib/gui/stats.py", line 358, in refresh
    self.stats = self.get_raw()
  File "/home/telecast/Documents/faceswap/lib/gui/stats.py", line 370, in get_raw
    loss_dict = self.session.total_loss if self.is_totals else self.session.loss
  File "/home/telecast/Documents/faceswap/lib/gui/stats.py", line 144, in loss
    loss_dict = self.tb_logs.get_loss(session=self.session_id)[self.session_id]
  File "/home/telecast/Documents/faceswap/lib/gui/stats.py", line 67, in get_loss
    for event in tf.train.summary_iterator(logfile):
  File "/home/telecast/Documents/faceswap_env/lib/python3.6/site-packages/tensorflow/python/summary/summary_iterator.py", line 68, in summary_iterator
    for r in tf_record.tf_record_iterator(path):
  File "/home/telecast/Documents/faceswap_env/lib/python3.6/site-packages/tensorflow/python/lib/io/tf_record.py", line 181, in tf_record_iterator
    reader.GetNext()
  File "/home/telecast/Documents/faceswap_env/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 489, in GetNext
    return _pywrap_tensorflow_internal.PyRecordReader_GetNext(self)
tensorflow.python.framework.errors_impl.DataLossError: truncated record at 305961

**Comment by torzdf** [comment] 2019-03-11 14:45
Unfortunately this looks like corruption in one of your logfiles
```tensorflow.python.framework.errors_impl.DataLossError: truncated record at 305961```
How many logfiles do you have? Would you be able to zip up the log folder and put it somewhere for me to download and have a look to see whether I can handle this error

**Comment by telecast-git** [comment] 2019-03-11 18:54
Do you need logs of faceswap only or OS too?

**Comment by torzdf** [comment] 2019-03-11 19:51
It's the tensorboard logs that are stored in your model folder that I need. They just contain the loss history

**Comment by telecast-git** [comment] 2019-03-12 07:44
Hi @torzdf
Logs:https://www.dropbox.com/s/lhf5e7k08jgfrkg/villain_logs.zip?dl=0

**Comment by torzdf** [comment] 2019-03-12 16:47
Is this definitely from a model that has started training? There's no loss records in it, just the graph definition
![image](https://user-images.githubusercontent.com/36920800/54219010-88cfd700-44e6-11e9-9540-2d7c773b8c11.png)

**Comment by torzdf** [comment] 2019-03-12 16:48
This may be a TF/TB 1.13 related issue. Unfortunately we only officially support up to 1.12 at the moment.

**Comment by telecast-git** [comment] 2019-03-12 17:14
> Is this definitely from a model that has started training?

Yes, this logs from model which must have info about 1000 epoch.

> This may be a TF/TB 1.13 related issue. 

Ок. I will try to compile TF/TB 1.12 for cuda 10.0 and cudnn v7.4.1.5, and see would be working the graph 

Thank you!

**Comment by spackofatzo** [comment] 2019-03-12 17:31
Just tested on a fresh environment, got the same error in the gui and graph is not showing.
But training works anyways.

**Comment by torzdf** [comment] 2019-03-12 17:33
Ok, this is a tf 1.13 then most likely. We use the Keras callback to log for tensorboard. I would guess that Keras backend has not been updated.

**Comment by telecast-git** [comment] 2019-03-12 17:45
I made downgrade TF/TB to 1.12 but bug is still (
<pre>
$ pip3 list | grep -e "tensorflow"
tensorflow-estimator         1.13.0
tensorflow-gpu               1.12.0

~$ pip3 list | grep -e "tensorboard"
tensorboard                  1.12.2</pre>

The graph isn't showing and get error in gui "log":https://github.com/deepfakes/faceswap/issues/656#issuecomment-471565261

**Comment by telecast-git** [comment] 2019-03-12 17:50
> Just tested on a fresh environment, got the same error in the gui and graph is not showing.
> But training works anyways.
Yes, training works, but without graph is not clear

**Comment by torzdf** [comment] 2019-03-12 18:08
Can you run a couple of iterations with loglevel TRACE and provide the faceswap.log.

Don't leave it running long as it will generate a huge amount of data.

**Comment by telecast-git** [comment] 2019-03-12 21:34
for check:
1. I made checkout to tags/v0.90, the graph is showing
2. next step made upgrade TF/TB up to 1.13, the graph is still showing.
3. checkout to  tags/v0.95b, the graph isn't showing

> Can you run a couple of iterations with loglevel TRACE and provide the faceswap.log.

faceswap.log:https://www.dropbox.com/s/lb6wrmnbtz841av/faceswap.log.zip?dl=0
my env:
<pre>
:~/Documents/faceswap$ git describe --tags 
v0.95b-36-g80a6c73
<pre>
$ pip3 list | grep tensor
tensorboard             1.13.1  
tensorflow              1.13.1  
tensorflow-estimator    1.13.0  
tensorflow-gpu          1.13.1 
</pre>

**Comment by torzdf** [comment] 2019-03-12 23:45
The old graphing didn't use tensorboard logging.

**Comment by iWater0** [comment] 2019-05-19 05:31
2 May 17 22:18 .recent.json
 cat .recent.json 
[]
got this file, with 2bytes, only an empty list there.

same problem, graph won't show when under training after TF1.12 -> 1.13
tensorflow.python.framework.errors_impl.DataLossError: truncated record at XXX

**Comment by iWater0** [comment] 2019-05-19 23:02
> Is this definitely from a model that has started training? There's no loss records in it, just the graph definition
> ![image](https://user-images.githubusercontent.com/36920800/54219010-88cfd700-44e6-11e9-9540-2d7c773b8c11.png)

I have double checked and is pretty sure all sessions were in it... nevertheless training from new or continued from an old existing, error pops.

./original_logs/a/session_2
./original_logs/a/session_3
./original_logs/a/session_4
./original_logs/a/session_1
./original_logs/a
./original_logs/b/session_2
./original_logs/b/session_3
./original_logs/b/session_4
./original_logs/b/session_1
./original_logs/b

TensorBoard Logging upgration could be the issue.

**Comment by torzdf** [comment] 2019-05-19 23:12
Tensorboard/Tensorflow 1.13 is not currently officially supported. The Keras callback for logging on training does not appear to work correctly. Until this is fixed upstream, this is how it will be.

If you want/need logs, use Tensorflow 1.12

**Comment by nerotiger** [comment] 2019-05-19 23:25
> Tensorboard/Tensorflow 1.13 is not currently officially supported. The Keras callback for logging on training does not appear to work correctly. Until this is fixed upstream, this is how it will be.
> 
> If you want/need logs, use Tensorflow 1.12

This is not a must for now, I am using console just fine. 
One more thing to mention, even when it was working under 1.12, the graph only showed 2 iterations (of A, B) i.e. 4 points, and not update accordingly. Is this a designed feature or it supposed to tick?

**Comment by torzdf** [comment] 2019-05-19 23:26
It updates every save interval or when the refresh button is pressed.

**Comment by nerotiger** [comment] 2019-05-20 00:25
> It updates every save interval or when the refresh button is pressed.

@torzdf 
I have updated to your latest stats.py i.e. (Bugfix: GUI Analysis - Correctly report iterations and rate)
But still won't refresh every 5 steps. 

![def](https://user-images.githubusercontent.com/8183249/57990386-c9486400-7ad8-11e9-96e5-a8ce59b6355e.jpeg)

**Comment by torzdf** [comment] 2019-05-20 12:03
That screengrab shows another crash happening, but there was a bug in sys.info preventing it from showing.

Try again with latest code.

**Comment by nerotiger** [comment] 2019-05-20 13:30
> That screengrab shows another crash happening, but there was a bug in sys.info preventing it from showing.
> 
> Try again with latest code.

@torzdf 

checked-out the latest one, re-installed in a blank new environment, graph is still the same as before.
however, system.info is correct this time (no errors).

![sc2](https://user-images.githubusercontent.com/8183249/58025197-8329e980-7b46-11e9-90c8-ce5257992863.jpg)

**Comment by torzdf** [comment] 2019-05-20 15:09
This may be a macos specific issue. Unfortunately I do not currently have a mac to be able to test on.

**Comment by nerotiger** [comment] 2019-05-20 15:13
> This may be a macos specific issue. Unfortunately I do not currently have a mac to be able to test on.

It's all right, thank you. Indeed and there is no refresh button as you described on Mac. 
If I have spare time, I may dig into this later, never touched X11 Gui before...

**Comment by torzdf** [comment] 2019-06-12 21:36
Logging in tf1.13.1 is now supported.

**Closed by torzdf** 2019-06-12 21:36 UTC

**Comment by procule** [comment] 2019-06-13 01:41
> Logging in tf1.13.1 is now supported.

Confirmed from local compiled version of tf1.13.1.
