### ISSUE TITLE
Fakeapp use low gpu

### ISSUE THREAD

**Issue by Damianuscz** [deepfakes/faceswap#74] opened 2018-01-27 18:37 UTC
I have a question about gpu usage. I have ryzen 1600x and nvidia 1060. When i run learning mode cpu run about 30 % and gpu Core about 10 and 20% vram is full 5gb. Is this normal? Learning proces run few hours at same %. Thx for answer and sorry for my english.

**Comment by Clorr** [comment] 2018-01-31 18:16
I can't tell you about fakeapp. If it does not use paralellization for image processing, maybe the cpu uses only one core, and then only few data is fed to the gpu which does not work full power. It is just a guess.

**Comment by Clorr** [comment] 2018-01-31 18:16
I'm closing this as it concerns fakeapp and I can't tell more about it

**Closed by Clorr** 2018-01-31 18:16 UTC

**Comment by FlamesoFF** [comment] 2019-07-23 14:08
@Clorr I think he meant "Faceswap", not "fakeapp".

**Comment by gessyoo** [comment] 2019-07-23 14:31
@FlamesoFF,  the problem is inherent to Windows 10's Task Manager.  Windows 10 GPU usage reporting is tailored towards gaming rather than deep-learning. If you a better estimate of GPU load during training, use nvidia-smi or a specific GPU monitoring utility, e.g. GPU-Z.

**Comment by torzdf** [comment] 2019-07-23 14:58
https://faceswap.dev/forum/app.php/faqpage#f0r3
