### ISSUE TITLE
Attepting to view Graph During Training Causes Crash

### ISSUE THREAD

**Issue by hackedintothemainframe** [deepfakes/faceswap#1195] opened 2021-12-04 19:45 UTC
**Describe the bug**
When attempting to open graphs by clicking the 'Graph' tab while training (I use the original trainer) the program crashes. 

**To Reproduce**
1. Create project, extract as normal, and train as normal (original trainer)
2. Click on 'the graph tab'
3. Crash

**Expected behavior**
A graph should appear

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Python Version: Latest Faceswap install (3.6?)
 - Conda Version: did not install through conda

**Crash Report**
[crash_report.2021.12.04.143315062239.log](https://github.com/deepfakes/faceswap/files/7654572/crash_report.2021.12.04.143315062239.log)

**Comment by torzdf** [comment] 2021-12-05 13:57
Hmmm, this issue appears entirely unrelated to clicking on the graph tab. The GUI code does not touch the base faceswap code in any way. The error you are seeing is being raised when python is trying to print the latest loss values. This is some very simple code and should not be failing in any way, indeed it has never failed here before to the best of my knowledge.

This suggests that the issue is in your setup somewhere, although I couldn't say where. Maybe running out of disk space?

Either way, I am closing this unless this issue is reported elsewhere...

The fact that your crash report cannot get your installed conda version, nor list the packages would also concern me, so I would do the following in the first instance and try again:

https://forum.faceswap.dev/app.php/faqpage?sid=12454a577bd3fc94b471dfa36ddcdcbe#f1r1

**Closed by torzdf** 2021-12-05 13:57 UTC
