### ISSUE TITLE
Can't use GPU

### ISSUE THREAD

**Issue by sdasdasddaaaa** [deepfakes/faceswap#1248] opened 2022-07-15 01:36 UTC
Excuse me, I have configured the GPU environment as required. When running the software, I found that the GPU is not running, but the CPU is running. How to solve this problem? Thanks!
![2345截图20220715071949](https://user-images.githubusercontent.com/87623989/179129303-2b4f5649-8c52-457e-983c-a338ebb528ca.jpg)
![2345截图20220715072142](https://user-images.githubusercontent.com/87623989/179129310-bfcc0ee7-f2a5-4f41-9168-021716eb4d59.jpg)

**Comment by torzdf** [comment] 2022-07-15 09:30
Duplicate of #1247 

Please don't reopen exactly the same issue

**Closed by torzdf** 2022-07-15 09:30 UTC
