### ISSUE TITLE
Missing dependency on "convert"

### ISSUE THREAD

**Issue by AlgorithMan-de** [deepfakes/faceswap#1203] opened 2022-01-15 20:22 UTC
Running on Windows 10 (german), I installed faceswap using the installer from https://faceswap.dev/
When I (try to) run it using the desktop-icon, nothing happens. So I started faceswap_win_launcer.bat from an (admin) cmd console and I get the following exception:

```
(faceswap) C:\Program Files\faceswap>"C:\Users\Admin\Miniconda3\scripts\activate.bat"   && conda activate "faceswap"   && python "C:\Programme\faceswap/faceswap.py" gui
Setting Faceswap backend to NVIDIA
Traceback (most recent call last):
  File "C:\Programme\faceswap/faceswap.py", line 55, in <module>
    _main()
  File "C:\Programme\faceswap/faceswap.py", line 40, in _main
    generate_configs()
  File "C:\Programme\faceswap\lib\config.py", line 487, in generate_configs
    mod.Config(None)
  File "C:\Programme\faceswap\lib\config.py", line 30, in __init__
    self.set_defaults()
  File "C:\Programme\faceswap\plugins\convert\_config.py", line 17, in set_defaults
    self._defaults_from_plugin(os.path.dirname(__file__))
  File "C:\Programme\faceswap\lib\config.py", line 88, in _defaults_from_plugin
    self._load_defaults_from_module(filename, import_path, plugin_type)
  File "C:\Programme\faceswap\lib\config.py", line 107, in _load_defaults_from_module
    mod = import_module("{}.{}".format(module_path, module))
  File "C:\Users\Admin\MiniConda3\envs\faceswap\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'convert'

```
This seems to be a missing dependency in the requirements, because the problem still exists after running pip install -r requirements_nvidia.txt
I tried to pip install convert, but that doesn't seem to install the right dependency, because then it instead complains about

```
File "<frozen importlib._bootstrap>", line 970, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'convert.color'; 'convert' is not a package
```

OS: Windows 10 (german)
Python Version: 3.8.12
Conda Version: 4.11.0
Commit: 183aee37e93708c0ae73845face5b4469319ebd3

**Comment by torzdf** [comment] 2022-01-15 23:00
Your environment is borked. There is no missing dependency. Convert is a part of faceswap.

As this is an issue with your setup and not with faceswap, I am closing this issue.

**Closed by torzdf** 2022-01-15 23:00 UTC

**Comment by AlgorithMan-de** [comment] 2022-01-16 11:26
I have done some more tests and it is a problem in the installer, which repeatably borks the environment unter certain circumstances.

As I said, I'm running on a german Windows 10.
The german Windows 10 has a directory `C:\Programme`, which is an alias for `C:\Program Files`, the actual directory that is hidden on german Windows versions.

Whenever I use `C:\Programme\faceswap` as target directory of the installation, I get the above error. When I install to `C:\Program Files\faceswap`, it works. It also works when I install to `C:\Users\Admin\faceswap`.

**Comment by gessyoo** [comment] 2022-01-21 20:04
Thousands of users have installed Faceswap under Windows 10 using the installer without the reporting the issue you have.  Please follow the install guide: https://forum.faceswap.dev/viewtopic.php?f=4&t=20.  Do not run the installer as an Administrator.  The default install directory is C:\Users\ ..... \faceswap, where .... represents the user name.  You should not be attempting to install faceswap to C:\Programme, or C:\Program Files.   If that's happening, then the issue is with your computer setup, not the installer.
