### ISSUE TITLE
Multiple GPUS training speeds are slower than 1 GPU

### ISSUE THREAD

**Issue by kuangzhongwen** [deepfakes/faceswap#709] opened 2019-04-18 16:32 UTC
**Describe the bug**
Multiple GPUS training speeds are slower than 1 GPU.

**To Reproduce**
When I used the GUI for training, the number of GPUS was 3, and I found that the training was slower than 1 GPU. Then I tested using 2 GPUS and the result was the same.

**Screenshots**
GPU status:
<img width="368" alt="Screen Shot 2019-04-19 at 00 26 05" src="https://user-images.githubusercontent.com/11549682/56376312-131fff00-623a-11e9-9a14-09743ad9b613.png">

1 GPU:
<img width="941" alt="单卡速度" src="https://user-images.githubusercontent.com/11549682/56376345-2a5eec80-623a-11e9-9e28-57121bdba105.png">

2 GPUS:
<img width="938" alt="双卡 gpu 状态" src="https://user-images.githubusercontent.com/11549682/56376366-33e85480-623a-11e9-8296-c1a88cce3a06.png">

**Desktop (please complete the following information):**
 - OS: ubuntu 16.04 LTS

**Comment by bryanlyon** [comment] 2019-04-18 17:43
Duplicate of #708

**Closed by bryanlyon** 2019-04-18 17:43 UTC
